### ISSUE TITLE
Loads in Home.app, but crashes Homebridge when interacted with

### ISSUE THREAD

**Issue by chrisbrummel** [grzegorz914/homebridge-lgwebos-tv#1]
I get the device to display correctly, but I get this crash when I try to change an input or press power:
`[Homebridge] [3/12/2020, 18:42:00] TypeError: Cannot read property 'lgtv' of undefined
    at /home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:532:11
    at lgwebosTvDevice.getInput (/home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:520:4)
    at lgwebosTvDevice.setInput (/home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:526:6)
    at Characteristic.ActiveIdentifier.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:310:10)
    at Characteristic.ActiveIdentifier.emit (events.js:210:5)
    at Characteristic.ActiveIdentifier.Characteristic.setValue (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Characteristic.js:323:10)
    at Accessory.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:882:22)
    at Array.forEach (<anonymous>)
    at Accessory._handleSetCharacteristics (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/Accessory.js:822:8)
    at HAPServer.emit (events.js:210:5)
    at HAPServer._handleCharacteristics (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/HAPServer.js:974:10)
    at HAPServer.<anonymous> (/home/hoobs/.hoobs/node_modules/@hoobs/hap/lib/HAPServer.js:209:39)
    at IncomingMessage.emit (events.js:210:5)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[Homebridge] [3/12/2020, 18:42:00] Got SIGTERM, shutting down service...`

-------- LG TV --------
Manufacturer: LG Electronics
Model: HU80KS-NA
System: webOSTV 3.5
Serialnumber: 20:17:42:18:f9:b8
Firmware: 00.11

**Comment by chrisbrummel** [comment]
I just ran the latest update and it looks like it's fixed. Thanks!
