### ISSUE TITLE
reporting incorrect power state. and more

### ISSUE THREAD

**Issue by OrigSorceror** [grzegorz914/homebridge-lgwebos-tv#101]
TV is turned on. but homebridge reports
[29/07/2021, 22:32:41] [LgWebOsTv] Device: <IP removed> LG TV, get current Power state successfull, state: OFF

also it can be turned on from HomeKit/Siri  but because it returns to the state saying it is powered off, homeKit and Siri is unable to turn it off. 

Just using standard config. 
{
            "devices": [
                {
                    "name": "LG TV",
                    "host": <Has correct IP>,
                    "mac": <is reporting correctly>,
                    "refreshInterval": 5,
                    "disableLogInfo": false,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "Live TV",
                            "reference": "com.webos.app.livetv",
                            "type": "TUNER",
                            "mode": 0
                        },
                        {
                            "name": "HDMI 1",
                            "reference": "com.webos.app.hdmi1",
                            "type": "HDMI",
                            "mode": 0
                        },
                        {
                            "name": "HDMI 2",
                            "reference": "com.webos.app.hdmi2",
                            "type": "HDMI",
                            "mode": 0
                        },
                        {
                            "name": "HDMI 3",
                            "reference": "com.webos.app.hdmi3",
                            "type": "HDMI",
                            "mode": 0
                        },
                        {
                            "name": "HDMI 4",
                            "reference": "com.webos.app.hdmi4",
                            "type": "HDMI",
                            "mode": 0
                        },
                        {
                            "name": "Netflix",
                            "reference": "netflix",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "YouTube",
                            "reference": "youtube.leanback.v4",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "LG Store",
                            "reference": "com.webos.app.discovery",
                            "type": "APPLICATION",
                            "mode": 0
                        }
                    ]
                }
            ],
            "platform": "LgWebOsTv"
        },

**Comment by grzegorz914** [comment]
What a TV?, any log in debug mode?

**Comment by OrigSorceror** [comment]
this is what is being reported in the logs when TV is turned on (manually or via homekit)  <IP addresses Removed>
[30/07/2021, 00:16:48] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, connected.
[30/07/2021, 00:16:48] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, RC Socket connected.
[30/07/2021, 00:16:49] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, state: Online.
[30/07/2021, 00:16:49] [LgWebOsTv] -------- LG TV --------
[30/07/2021, 00:16:49] [LgWebOsTv] Manufacturer: LG Electronics
[30/07/2021, 00:16:49] [LgWebOsTv] Model: 65UF950T-TA
[30/07/2021, 00:16:49] [LgWebOsTv] System: webOSTV 2.0
[30/07/2021, 00:16:49] [LgWebOsTv] Serialnr: 3c:cd:93:f9:95:1d
[30/07/2021, 00:16:49] [LgWebOsTv] Firmware: 04.06.00
[30/07/2021, 00:16:49] [LgWebOsTv] ----------------------------------

then reports the following every 10 seconds (whilst TV is on or Off) <IP addresses Removed>
[30/07/2021, 00:19:09] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, get current Power state successfull, state: OFF
[30/07/2021, 00:19:09] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, get current Input successful: Live TV com.webos.app.livetv
[30/07/2021, 00:19:09] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, get current Mute state successful: ON
[30/07/2021, 00:19:09] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, get current Volume level successful: 0
[30/07/2021, 00:19:09] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, Input: Live TV, get target visibility state: SHOWN
[30/07/2021, 00:19:09] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, Input: HDMI 1, get target visibility state: SHOWN
[30/07/2021, 00:19:09] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, Input: HDMI 2, get target visibility state: SHOWN
[30/07/2021, 00:19:09] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, Input: HDMI 3, get target visibility state: SHOWN
[30/07/2021, 00:19:09] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, Input: HDMI 4, get target visibility state: SHOWN
[30/07/2021, 00:19:09] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, Input: Netflix, get target visibility state: SHOWN
[30/07/2021, 00:19:09] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, Input: YouTube, get target visibility state: SHOWN
[30/07/2021, 00:19:09] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, Input: LG Store, get target visibility state: SHOWN

**Comment by grzegorz914** [comment]
webOS 2.0 here is the problem, please enable debug mode in Homebridge and then get the log.

**Comment by OrigSorceror** [comment]
Here's the debug log after turning on the TV from within homeKit


[30/07/2021, 11:10:15] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, set new Power state successful: ON
[30/07/2021, 11:10:35] [homebridge-lgwebos-tv] This plugin threw an error from the characteristic 'Volume': Unhandled error thrown inside write handler for characteristic: Cannot read property 'request' of undefined. See https://git.io/JtMGR for more info.
[30/07/2021, 11:10:35] [homebridge-lgwebos-tv] TypeError: Cannot read property 'request' of undefined
    at Volume.setHandler (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:634:15)
    at Volume.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1588:42)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Volume.Characteristic.handleSetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:791:24)
    at Volume.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1307:10)
    at TelevisionSpeaker.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:459:35)
[30/07/2021, 11:10:35] [homebridge-lgwebos-tv] This plugin threw an error from the characteristic 'Volume': Unhandled error thrown inside write handler for characteristic: Cannot read property 'request' of undefined. See https://git.io/JtMGR for more info.
[30/07/2021, 11:10:35] [homebridge-lgwebos-tv] TypeError: Cannot read property 'request' of undefined
    at Volume.setHandler (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:634:15)
    at Volume.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1588:42)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Volume.Characteristic.handleSetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:791:24)
    at Volume.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1307:10)
    at TelevisionSpeaker.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:459:35)
[30/07/2021, 11:10:35] [homebridge-lgwebos-tv] This plugin threw an error from the characteristic 'Volume': Unhandled error thrown inside write handler for characteristic: Cannot read property 'request' of undefined. See https://git.io/JtMGR for more info.
[30/07/2021, 11:10:35] [homebridge-lgwebos-tv] TypeError: Cannot read property 'request' of undefined
    at Volume.setHandler (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:634:15)
    at Volume.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1588:42)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Volume.Characteristic.handleSetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:791:24)
    at Volume.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1307:10)
    at TelevisionSpeaker.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:459:35)
[30/07/2021, 11:10:36] [homebridge-lgwebos-tv] This plugin threw an error from the characteristic 'Volume': Unhandled error thrown inside write handler for characteristic: Cannot read property 'request' of undefined. See https://git.io/JtMGR for more info.
[30/07/2021, 11:10:36] [homebridge-lgwebos-tv] TypeError: Cannot read property 'request' of undefined
    at Volume.setHandler (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:634:15)
    at Volume.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1588:42)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
    at Object.next (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:124:57)
    at /usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:113:16)
    at Volume.Characteristic.handleSetRequest (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:791:24)
    at Volume.Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1307:10)
    at TelevisionSpeaker.Service.setCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:459:35)
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, connecting to TV
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, connecting...
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, connect error: Error: Sec-WebSocket-Accept header from server didn't match expected value of gq5TBtgu46BZd4Sl6bfNCtrSbGk=
    at WebSocketClient.failHandshake (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:339:32)
    at WebSocketClient.validateHandshake (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:326:14)
    at ClientRequest.handleRequestUpgrade (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:261:14)
    at ClientRequest.emit (events.js:375:28)
    at Socket.socketOnData (_http_client.js:553:11)
    at Socket.emit (events.js:375:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, connected.
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, connecting to TV RC Socket
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, RC Socket connected.
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, requesting Device Info.
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, requesting device state.
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, get current Power state data: {}
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, get current App state response: {
  appId: 'com.webos.app.livetv',
  subscribed: true,
  returnValue: true,
  windowId: '',
  processId: 'n-1243'
}
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, get System info response: {
  features: [Object],
  receiverType: 'dvb',
  modelName: '65UF950T-TA',
  returnValue: true
}
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, get current Audio state response: {
  scenario: 'mastervolume_ext_speaker_arc',
  active: false,
  action: 'requested',
  volume: 0,
  returnValue: true,
  subscribed: true,
  mute: false,
  changed: [Array]
}
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, get current Channel response: {
  subscribed: true,
  channelId: '1_25_12_12_1541_1623_4116',
  signalChannelId: '1541_1623_4116',
  channelModeId: 0,
  channelModeName: 'Terrestrial',
  channelTypeId: 1,
  channelTypeName: 'Terrestrial Digital TV',
  channelNumber: '12',
  channelName: '10 BOLD',
  physicalNumber: 25,
  isSkipped: false,
  isLocked: false,
  isDescrambled: false,
  isScrambled: false,
  isFineTuned: false,
  isInvisible: false,
  isHEVCChannel: false,
  favoriteGroup: null,
  hybridtvType: 'HBBTV',
  dualChannel: [Object],
  returnValue: true
}
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, get System info response1: {
  returnValue: true,
  product_name: 'webOSTV 2.0',
  model_name: 'HE_DTV_W15H_AFADABAA',
  sw_type: 'FIRMWARE',
  major_ver: '04',
  minor_ver: '06.00',
  country: 'AU',
  device_id: '3c:cd:93:f9:95:1d',
  auth_flag: 'N',
  ignore_disable: 'N',
  eco_info: '01',
  config_key: '00',
  language_code: 'en-AU'
}
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, saved Device Info successful: {
  "features": {
    "3d": true,
    "dvr": true
  },
  "receiverType": "dvb",
  "modelName": "65UF950T-TA",
  "returnValue": true,
  "product_name": "webOSTV 2.0",
  "model_name": "HE_DTV_W15H_AFADABAA",
  "sw_type": "FIRMWARE",
  "major_ver": "04",
  "minor_ver": "06.00",
  "country": "AU",
  "device_id": "3c:cd:93:f9:95:1d",
  "auth_flag": "N",
  "ignore_disable": "N",
  "eco_info": "01",
  "config_key": "00",
  "language_code": "en-AU"
}
[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, state: Online.
[30/07/2021, 11:10:41] [LgWebOsTv] -------- LG TV --------
[30/07/2021, 11:10:41] [LgWebOsTv] Manufacturer: LG Electronics
[30/07/2021, 11:10:41] [LgWebOsTv] Model: 65UF950T-TA
[30/07/2021, 11:10:41] [LgWebOsTv] System: webOSTV 2.0
[30/07/2021, 11:10:41] [LgWebOsTv] Serialnr: 3c:cd:93:f9:95:1d
[30/07/2021, 11:10:41] [LgWebOsTv] Firmware: 04.06.00
[30/07/2021, 11:10:41] [LgWebOsTv] ----------------------------------
[30/07/2021, 11:10:42] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, get apps list response2: { apps: [Array], returnValue: true }
[30/07/2021, 11:10:42] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, write apps list: [
  {
    "name": "LG Content Store",
    "reference": "com.webos.app.discovery"
  },
  {
    "name": "Netflix",
    "reference": "netflix"
  },
  {
    "name": "Stan",
    "reference": "stan.webos2"
  },
  {
    "name": "YuppTV",
    "reference": "yupptv"
  },
  {
    "name": "Amazon Prime Video",
    "reference": "amazon.global"
  },
  {
    "name": "PREMIER",
    "reference": "tntwebapp"
  },
  {
    "name": "Live TV",
    "reference": "com.webos.app.livetv"
  },
  {
    "name": "Web Browser",
    "reference": "com.webos.app.browser"
  },
  {
    "name": "User Guide",
    "reference": "com.webos.app.tvuserguide"
  },
  {
    "name": "Device Connector",
    "reference": "com.webos.app.connectionwizard"
  },
  {
    "name": "SmartShare",
    "reference": "com.webos.app.smartshare"
  },
  {
    "name": "Scheduler",
    "reference": "com.webos.app.scheduler"
  },
  {
    "name": "Screen Share",
    "reference": "com.webos.app.miracast"
  },
  {
    "name": "TV Guide",
    "reference": "com.webos.app.tvguide"
  },
  {
    "name": "LG Photo Editor",
    "reference": "com.webos.app.capturetv"
  },
  {
    "name": "Camera",
    "reference": "com.webos.app.camera"
  },
  {
    "name": "Notifications",
    "reference": "com.webos.app.notificationcenter"
  },
  {
    "name": "Advertisement",
    "reference": "com.webos.app.adapp"
  },
  {
    "name": "Brand Shop",
    "reference": "com.webos.app.brandshop"
  },
  {
    "name": "InputCommon",
    "reference": "com.webos.app.inputcommon"
  },
  {
    "name": "Thirdparty Login",
    "reference": "com.webos.app.facebooklogin"
  },
  {
    "name": "LG Membership",
    "reference": "com.webos.app.membership"
  },
  {
    "name": "First Use",
    "reference": "com.palm.app.firstuse"
  },
  {
    "name": "Accessibility",
    "reference": "com.palm.app.settings"
  },
  {
    "name": "Camera Gallery",
    "reference": "com.webos.app.cameragallery"
  },
  {
    "name": "PROGRAMME MANAGER",
    "reference": "com.webos.app.channeledit"
  },
  {
    "name": "Programme Tuning",
    "reference": "com.webos.app.channelsetting"
  },
  {
    "name": "Cheering Mode",
    "reference": "com.webos.app.cheeringtv"
  },
  {
    "name": "Enyo (2.3.0) App Container",
    "reference": "com.webos.app.container"
  },
  {
    "name": "Connected Red Button",
    "reference": "com.webos.app.crb"
  },
  {
    "name": "Customer Support",
    "reference": "com.webos.app.customersupport"
  },
  {
    "name": "Local Control Panel",
    "reference": "com.webos.app.dvrpopup"
  },
  {
    "name": "AV",
    "reference": "com.webos.app.externalinput.av1"
  },
  {
    "name": "AV2",
    "reference": "com.webos.app.externalinput.av2"
  },
  {
    "name": "Component",
    "reference": "com.webos.app.externalinput.component"
  },
  {
    "name": "AV1",
    "reference": "com.webos.app.externalinput.scart"
  },
  {
    "name": "HDMI1",
    "reference": "com.webos.app.hdmi1"
  },
  {
    "name": "HDMI2",
    "reference": "com.webos.app.hdmi2"
  },
  {
    "name": "HDMI3",
    "reference": "com.webos.app.hdmi3"
  },
  {
    "name": "HDMI4",
    "reference": "com.webos.app.hdmi4"
  },
  {
    "name": "Input Hub",
    "reference": "com.webos.app.inputmgr"
  },
  {
    "name": "Installation Settings",
    "reference": "com.webos.app.installation"
  },
  {
    "name": "LiveMenuPlayerAV1",
    "reference": "com.webos.app.livemenuplayer-inav1"
  },
  {
    "name": "LiveMenuPlayerAV2",
    "reference": "com.webos.app.livemenuplayer-inav2"
  },
  {
    "name": "LiveMenuPlayerComponent",
    "reference": "com.webos.app.livemenuplayer-incomponent"
  },
  {
    "name": "LiveMenuPlayerHdmi1",
    "reference": "com.webos.app.livemenuplayer-inhdmi1"
  },
  {
    "name": "LiveMenuPlayerHdmi2",
    "reference": "com.webos.app.livemenuplayer-inhdmi2"
  },
  {
    "name": "LiveMenuPlayerHdmi3",
    "reference": "com.webos.app.livemenuplayer-inhdmi3"
  },
  {
    "name": "LiveMenuPlayerHdmi4",
    "reference": "com.webos.app.livemenuplayer-inhdmi4"
  },
  {
    "name": "LiveMenuPlayerScart",
    "reference": "com.webos.app.livemenuplayer-inscart"
  },
  {
    "name": "LiveMenuPlayerTV",
    "reference": "com.webos.app.livemenuplayer-intv"
  },
  {
    "name": "Live Zoom App",
    "reference": "com.webos.app.livezoom-inhdmi1"
  },
  {
    "name": "Live Zoom App",
    "reference": "com.webos.app.livezoom-inhdmi2"
  },
  {
    "name": "Live Zoom App",
    "reference": "com.webos.app.livezoom-inhdmi3"
  },
  {
    "name": "Live Zoom App",
    "reference": "com.webos.app.livezoom-inhdmi4"
  },
  {
    "name": "Live Zoom App",
    "reference": "com.webos.app.livezoom-intv"
  },
  {
    "name": "MVPDWin",
    "reference": "com.webos.app.mvpdwin"
  },
  {
    "name": "Remote Setting",
    "reference": "com.webos.app.remotesetting"
  },
  {
    "name": "Screen Saver",
    "reference": "com.webos.app.screensaver"
  },
  {
    "name": "Software Update",
    "reference": "com.webos.app.softwareupdate"
  },
  {
    "name": "Store Demo",
    "reference": "com.webos.app.store-demo"
  },
  {
    "name": "Local Control Panel",
    "reference": "com.webos.app.tvhotkey"
  },
  {
    "name": "Viewer",
    "reference": "com.webos.app.tvsimpleviewer"
  },
  {
    "name": "Adjust camera angle",
    "reference": "com.webos.app.tvtutorial"
  },
  {
    "name": "Voice App",
    "reference": "com.webos.app.voice"
  },
  {
    "name": "Web App",
    "reference": "com.webos.app.webapphost"
  },
  {
    "name": "Aquarium 3D",
    "reference": "com.xstars.app.aquarium"
  },
  {
    "name": "SBS on Demand",
    "reference": "sbs"
  },
  {
    "name": "TV Cast",
    "reference": "de.2kit.castbrowserlg"
  },
  {
    "name": "Plex",
    "reference": "cdp-30"
  },
  {
    "name": "9Now",
    "reference": "com.accedo.mi9.prod"
  },
  {
    "name": "Emby",
    "reference": "com.emby.app"
  },
  {
    "name": "YouTube",
    "reference": "youtube.leanback.v4"
  },
  {
    "name": "SoPlayer",
    "reference": "soplayer"
  }
]
[30/07/2021, 11:10:49] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, set new Volume level successful: 15
[30/07/2021, 11:10:49] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, get current Audio state response: {
  changed: [Array],
  returnValue: true,
  cause: 'setVolume',
  scenario: 'mastervolume_ext_speaker_arc',
  volume: 15,
  action: 'changed',
  active: false,
  mute: false
}
[30/07/2021, 11:10:50] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, set new Volume level successful: 18
[30/07/2021, 11:10:50] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, get current Audio state response: {
  changed: [Array],
  returnValue: true,
  cause: 'setVolume',
  scenario: 'mastervolume_ext_speaker_arc',
  volume: 18,
  action: 'changed',
  active: false,
  mute: false
}

**Comment by 7RDR7** [comment]
Experiencing the same issues as OrigSorceror

**Comment by grzegorz914** [comment]
Your TV webOS 2.0 doesn’t respond on power state check
`[30/07/2021, 11:10:41] [LgWebOsTv] Device: xxx.xxx.xxx.xxx LG TV, get current Power state data: {} `

**Comment by OrigSorceror** [comment]
I have now uninstalled this plugin and installed the plugin by merdok (https://github.com/merdok/homebridge-webos-tv#readme), His implementation of the power state actually works. It was the original plugin i was using on my homebridge before the Pi became corrupted. 

Thanks for the effort though..

**Comment by 7RDR7** [comment]
Thanks @OrigSorceror OrigSorceror. Appreciate the recommendation. I switched as well, and all working great.

**Comment by grzegorz914** [comment]
please check latest version 1.8.9
