### ISSUE TITLE
Homebridge Process Ended. Code: null, Signal: SIGBUS

### ISSUE THREAD

**Issue by alexsalex** [grzegorz914/homebridge-lgwebos-tv#108]
After last update HB always rebooted.

```
[9/26/2021, 4:42:01 PM] [LgWebOsTv] Device: 10.0.1.8 Living Room TV, connecting to TV RC Socket
[9/26/2021, 4:42:01 PM] [HB Supervisor] Homebridge Process Ended. Code: null, Signal: SIGBUS
```

**Comment by alexsalex** [comment]
[9/26/2021, 4:43:39 PM] [LgWebOsTv] Device: 10.0.1.8 Living Room TV, connect error: Error: Sec-WebSocket-Accept header from server didn't match expected value of iHTXoizcAzGJDnY0ghLucVyePhA=
    at WebSocketClient.failHandshake (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:339:32)
    at WebSocketClient.validateHandshake (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:326:14)
    at ClientRequest.handleRequestUpgrade (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:261:14)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketOnData (_http_client.js:553:11)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

**Comment by alexsalex** [comment]
`[9/26/2021, 4:44:09 PM] [LgWebOsTv] Device: 10.0.1.8 Living Room TV, connecting...
[9/26/2021, 4:44:09 PM] [LgWebOsTv] Device: 10.0.1.8 Living Room TV, connect error: Error: Sec-WebSocket-Accept header from server didn't match expected value of JYcrzlrr8Ix3kbDn1pckNSM4SOI=
    at WebSocketClient.failHandshake (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:339:32)
    at WebSocketClient.validateHandshake (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:326:14)
    at ClientRequest.handleRequestUpgrade (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:261:14)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketOnData (_http_client.js:553:11)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[9/26/2021, 4:44:09 PM] [LgWebOsTv] Device: 10.0.1.8 Living Room TV, waiting on confirmation...
[9/26/2021, 4:44:09 PM] [LgWebOsTv] Device: 10.0.1.8 Living Room TV, waiting on confirmation...
[9/26/2021, 4:44:09 PM] [LgWebOsTv] Device: 10.0.1.8 Living Room TV, waiting on confirmation...
[9/26/2021, 4:44:14 PM] [LgWebOsTv] Device: 10.0.1.8 Living Room TV, connecting to TV
[9/26/2021, 4:44:14 PM] [LgWebOsTv] Device: 10.0.1.8 Living Room TV, connecting...
[9/26/2021, 4:44:14 PM] [LgWebOsTv] Device: 10.0.1.8 Living Room TV, connect error: Error: Sec-WebSocket-Accept header from server didn't match expected value of 0bIfVy4HmLq1QhYi4l+oD9qYrks=
    at WebSocketClient.failHandshake (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:339:32)
    at WebSocketClient.validateHandshake (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:326:14)
    at ClientRequest.handleRequestUpgrade (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:261:14)
    at ClientRequest.emit (events.js:400:28)
    at Socket.socketOnData (_http_client.js:553:11)
    at Socket.emit (events.js:400:28)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)
    at Socket.Readable.push (internal/streams/readable.js:204:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[9/26/2021, 4:44:14 PM] [LgWebOsTv] Device: 10.0.1.8 Living Room TV, waiting on confirmation...
[9/26/2021, 4:44:14 PM] [LgWebOsTv] Device: 10.0.1.8 Living Room TV, waiting on confirmation...
[9/26/2021, 4:44:14 PM] [LgWebOsTv] Device: 10.0.1.8 Living Room TV, waiting on confirmation...`

**Comment by JimmyDaGeek** [comment]
I have been experiencing this issue too.

Note that if it is an authentication error it should be trapped instead of crashing the plugin, so even if the cause is something to do with the WEBOS API, Homebridge shouldn't just sit there and go into a restart loop like it does now.

My problem just started happening yesterday midday.

**Comment by grzegorz914** [comment]
This is very strange error SIGBUS and also happened be me too. It’s not related to the plugin it self. I will investigate into this and will report what’s going on.

**Comment by JimmyDaGeek** [comment]
Note that this is only happening when one of the TV sets is on.  When both are powered off (software power) Homebridge is functional.
Homebridge is also functional when the plugin is disabled.  I will revert to your prior version to see if that resolves the issue.

**Comment by alexsalex** [comment]
Any updates on investigation?

**Comment by grzegorz914** [comment]
please go to console and run this:
`cd /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules`
`sudo npm install bufferutil@4.0.3`
