### ISSUE TITLE
Missing inputs file

### ISSUE THREAD

**Issue by angyp** [grzegorz914/homebridge-lgwebos-tv#11]
Seem to be missing a file was never generated during install. Homebridge also crashes when trying to switch inputs on the home app.

`[4/22/2020, 8:27:17 PM] [LgWebOsTv] Device: 192.168.15.143, read inputsFile failed, error: Error: ENOENT: no such file or directory, open '/root/.homebridge/lgwebosTv/inputs_19216815143'
    at Object.openSync (fs.js:461:3)
    at Object.readFileSync (fs.js:363:35)
    at lgwebosTvDevice.prepareInputServices (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:424:31)
    at lgwebosTvDevice.prepareTvService (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:385:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/root/.homebridge/lgwebosTv/inputs_19216815143'
`

`[4/22/2020, 8:40:50 PM] [LgWebOsTv] Device: 192.168.15.143, get current Input successful: com.webos.app.hdmi1
[4/22/2020, 8:40:50 PM] [LgWebOsTv] Device: 192.168.15.143, set new Input successful: function() {
    if (called) {
      throw new Error("This callback function has already been called by someone else; it can only be called one time.");
    }
    else {
      called = true;
      return func.apply(this, arguments);
    }
  }
[4/22/2020, 8:40:50 PM] Got SIGTERM, shutting down Homebridge.`

**Comment by angyp** [comment]
Was able to get the input file created using a hint from previously closed issue. However, still can't switch inputs.

**Comment by angyp** [comment]
Works now. Reversed the changes in line 583 of index.js made in commit 06b599e

**Comment by grzegorz914** [comment]
Fixed.

**Comment by angyp** [comment]
Thanks. Confirmed resolved.
