### ISSUE TITLE
Error During installation

### ISSUE THREAD

**Issue by iceage2609** [grzegorz914/homebridge-lgwebos-tv#126]
Hi there, i have installed Homebridge on my DS118 Synology NAS without docker , using the latest version here [https://github.com/oznu/homebridge-syno-spk/releases/tag/2.2.1](url) 
As the developer said Synology does not allow native packages to have any sudo / admin privileges as of DSM 7.
So i don't know if that's causing the issue with your plug in during installation. I use node 16.14.2

I am getting this : 
`pm ERR! code 1
npm ERR! path /volume1/@appdata/homebridge/lib/node_modules/homebridge-lgwebos-tv/node_modules/utf-8-validate
npm ERR! command failed
npm ERR! command sh -c node-gyp-build
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.14.2 | linux | arm64
npm ERR! gyp info find Python using Python version 3.8.8 found at "/usr/bin/python3.8"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.2/node-v16.14.2-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.14.2/SHASUMS256.txt
npm ERR! gyp info spawn /usr/bin/python3.8
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/volume1/@appdata/homebridge/lib/node_modules/homebridge-lgwebos-tv/node_modules/utf-8-validate/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/var/packages/homebridge/home/.cache/node-gyp/16.14.2/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/var/packages/homebridge/home/.cache/node-gyp/16.14.2',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/var/packages/homebridge/home/.cache/node-gyp/16.14.2/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/volume1/@appdata/homebridge/lib/node_modules/homebridge-lgwebos-tv/node_modules/utf-8-validate',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 4.4.180+
npm ERR! gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /volume1/@appdata/homebridge/lib/node_modules/homebridge-lgwebos-tv/node_modules/utf-8-validate
npm ERR! gyp ERR! node -v v16.14.2
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/packages/homebridge/home/.npm/_logs/2022-04-04T09_14_44_502Z-debug-0.log

`

**Comment by iceage2609** [comment]
Thanks, i will
