### ISSUE TITLE
Volume control

### ISSUE THREAD

**Issue by angyp** [grzegorz914/homebridge-lgwebos-tv#13]
Hi is the volume control dimmer supposed to work with all WebOS TV's? I have an OLED65C7 and it doesn't work. I can control the volume using apple TV remote in control centre but not from the brightness and thus not from Siri either. Also, is the way of displaying the current TV channel when on live TV?

**Comment by angyp** [comment]
Interesting since I have upgraded to home bridge version 1.0.3 it now crashed when I attempt to change the volume using the brightness slider.  
[4/29/2020, 2:54:49 PM] Got SIGTERM, shutting down Homebridge... 
Debug turned on but no details. Sorry

**Comment by grzegorz914** [comment]
If U use sound output over arc-HDMI U can change Volume using hardware buttons, if U use TV speakers then hardware buttons, slider and Siri.

**Comment by grzegorz914** [comment]
> Interesting since I have upgraded to home bridge version 1.0.3 it now crashed when I attempt to change the volume using the brightness slider.
> [4/29/2020, 2:54:49 PM] Got SIGTERM, shutting down Homebridge...
> Debug turned on but no details. Sorry

Hmm, will check this.

**Comment by angyp** [comment]
Seems like the second issue has been resolved in 0.3.26 so Thankyou.

**Comment by grzegorz914** [comment]
Witch channels display is little difficulty, I will look on this in future.

**Comment by angyp** [comment]
Hi, Thanks for all your continued work on this plugin. I have noticed of late that the remote control doesn't work reliably can only turn the volume up or down one click. TV menu doesn't come up and the navigation buttons no longer work. Also, the TV power state has regressed. TV could be off but the home app states it's on most times it can be corrected by closing the home app and reopening.

**Comment by grzegorz914** [comment]
Any log during working with RC app?

**Comment by angyp** [comment]
I think I have worked out whats happening

When you first open the RC app it will take a single command then it won't take any more for the next 11 seconds then it seems to work. In this example, I opened the app pushed the volume up continually, First one went through the nothing for 11 seconds.   Jump out of the remote and back in and the same thing happens again.

[5/15/2020, 3:09:20 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, setVolumeSelector successful, remoteKey: 0, command: VOLUMEUP
[5/15/2020, 3:09:20 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Mute state: OFF
[5/15/2020, 3:09:20 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Volume level: 9
[5/15/2020, 3:09:31 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, setVolumeSelector successful, remoteKey: 0, command: VOLUMEUP
[5/15/2020, 3:09:31 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Mute state: OFF
[5/15/2020, 3:09:31 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Volume level: 10
[5/15/2020, 3:09:31 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, setVolumeSelector successful, remoteKey: 0, command: VOLUMEUP
[5/15/2020, 3:09:31 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Mute state: OFF
[5/15/2020, 3:09:31 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Volume level: 11
[5/15/2020, 3:09:32 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, setVolumeSelector successful, remoteKey: 0, command: VOLUMEUP
[5/15/2020, 3:09:32 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Mute state: OFF

**Comment by angyp** [comment]
Then sometimes the RC app just bombs out with "Can't Connect to TV error" also sometimes I open the RC app and the Lounge TV isn't listed only my apple TV.

**Comment by grzegorz914** [comment]
That U have problem with connection to TV, check your NET, firewall etc.. , I tested all the buttons in RC and all working correct on all my 3 TVs. Looks on Your log all seems to be OK.

**Comment by angyp** [comment]
I am confident it's not a connection issue. It was working perfectly in previous versions of your plugin. If it was a TV connection issue the logs should show me pressing buttons during the 11 seconds gap in the log.

**Comment by grzegorz914** [comment]
what a iOS U use,?
U can install previous version homebridge-lgwebos-tv@versionnumber 
and test again.

**Comment by angyp** [comment]
Running latest IOS 13.4.1. Happens on iPhone and iPad. Will try and find a working version but it's been a while since it's been reliable.

**Comment by angyp** [comment]
Downgraded to 0.7.68 and the RC app works perfectly however that version has other issues.

**Comment by grzegorz914** [comment]
make update to latest 0.9.13 and get the feedback

**Comment by angyp** [comment]
Just in the middle of isolating it down found it was ok in 0.8.1 and broken in 0.8.2. Just tired the latest 0.9.13 and it's still broken.

**Comment by grzegorz914** [comment]
OK, im revert the changes from 8.1 to latest 0.9.14, please test it

**Comment by grzegorz914** [comment]
wait little, npm is down right now I can not publish

**Comment by grzegorz914** [comment]
Update online

**Comment by angyp** [comment]
0.9.13 is the latest I see which I already have.

**Comment by grzegorz914** [comment]
0.9.15

**Comment by angyp** [comment]
0.9.15 is whacked I turn the volume down on the remote and it turns the TV off? not sure what's going on here the power state looks all mucked up. Home app TV state off but TV is on.

**Comment by grzegorz914** [comment]
0.9.17 online

**Comment by angyp** [comment]
Updated to the latest 0.9.34 and the power-on state is great. However, the off power state is no good even after you double-tap swipe up to close the home app still reports TV on when it's off. When I try to change the volume on the RV app the TV turns off.
`
[5/16/2020, 8:59:56 AM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, setVolumeSelector successful, remoteKey: 1, command: VOLUMEDOWN
[5/16/2020, 8:59:56 AM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Mute state: OFF
[5/16/2020, 8:59:56 AM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Volume level: 0
[5/16/2020, 8:59:56 AM] [LgWebOsTv] { returnValue: true, state: 'Active', processing: 'Request Power Off' }
[5/16/2020, 8:59:56 AM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Power state successful: ON
[5/16/2020, 8:59:56 AM] [LgWebOsTv] {
  returnValue: true,
  state: 'Active',
  processing: 'Request Active Standby'
}
[5/16/2020, 8:59:56 AM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Power state successful: ON
[5/16/2020, 8:59:56 AM] [LgWebOsTv] { returnValue: true, state: 'Active', processing: 'Request Suspend' }
[5/16/2020, 8:59:56 AM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Power state successful: ON
[5/16/2020, 8:59:56 AM] [LgWebOsTv] { returnValue: true, state: 'Active', processing: 'Prepare Suspend' }
[5/16/2020, 8:59:56 AM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Power state successful: ON
[5/16/2020, 8:59:56 AM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, set new Power state successful: STANDBY
[5/16/2020, 8:59:56 AM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, disconnected.
[5/16/2020, 8:59:56 AM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, disconnected. 
`

**Comment by grzegorz914** [comment]
Hi,
Please make 2 logs with debug mode:
1. power ON TV with RC control
2. power OFF TV with RC control

**Comment by angyp** [comment]
Just upgraded to the lates and now home bridge won't start.

[5/16/2020, 4:38:43 PM] ====================
[5/16/2020, 4:38:43 PM] ERROR LOADING PLUGIN homebridge-lgwebos-tv:
[5/16/2020, 4:38:43 PM] /usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:482
                        }
                        ^

SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at Module.Hook._require.Module.require (/usr/local/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/src/plugin.ts:162:27)
    at /usr/local/lib/node_modules/homebridge/src/pluginManager.ts:119:16
[5/16/2020, 4:38:43 PM] ====================
[5/16/2020, 4:38:44 PM] Error loading platform requested in your config.json at position 5
[5/16/2020, 4:38:44 PM] Error: The requested platform 'LgWebOsTv' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:223:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:386:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:373:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:152:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Object.<anonymous> (/usr/local/lib/node_modules/pm2/lib/ProcessContainerFork.js:32:23)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
[5/16/2020, 4:38:44 PM] [Config] Homebridge Config UI X v4.19.0 is listening on :: port 80

**Comment by grzegorz914** [comment]
upgrade again

**Comment by angyp** [comment]
Ok 

This is me opening the Home app while the TV was on. TV was on while the home bridge was restarted after update to 0.9.48

[5/16/2020, 4:52:05 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Power state successfull, state: ON
[5/16/2020, 4:52:05 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Input successful: cdp-30
[5/16/2020, 4:52:05 PM] [LgWebOsTv] Device: 192.168.15.143 4, get current Volume level successful: %s
[5/16/2020, 4:52:05 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Mute state successful: OFF

This is what happens when I turn the tv off using the TV remote control will the home app still open. Seems to work home app shows TV off.  

[5/16/2020, 4:55:57 PM] [LgWebOsTv] { returnValue: true, state: 'Active', processing: 'Request Power Off' }
[5/16/2020, 4:55:57 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Power state successful: ON
[5/16/2020, 4:55:57 PM] [LgWebOsTv] {
  returnValue: true,
  state: 'Active',
  processing: 'Request Active Standby'
}
[5/16/2020, 4:55:57 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Power state successful: ON
[5/16/2020, 4:55:57 PM] [LgWebOsTv] {
  returnValue: true,
  state: 'Active',
  processing: 'Prepare Active Standby'
}
[5/16/2020, 4:55:57 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Power state successful: ON
[5/16/2020, 4:55:58 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Input successful:
[5/16/2020, 4:55:59 PM] [LgWebOsTv] { returnValue: true, state: 'Active Standby' }
[5/16/2020, 4:55:59 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Power state successful: PIXEL REFRESH / STANDBY
[5/16/2020, 4:55:59 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, disconnected.
[5/16/2020, 4:55:59 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, disconnected.


No log output when I turn on the TV using the TV remote control Home app shows TV off .. Close the home app and re open following logs 

[5/16/2020, 4:59:32 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Power state successfull, state: STANDBY
[5/16/2020, 4:59:32 PM] [LgWebOsTv] Device: 192.168.15.143 3, get current Volume level successful: %s
[5/16/2020, 4:59:32 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Mute state successful: ON

Home app show it off although it's on.

**Comment by angyp** [comment]
If I restart home bridge and open the home app again it shows the correct state.

[5/16/2020, 5:04:19 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Power state successfull, state: ON
[5/16/2020, 5:04:19 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Input successful: cdp-30
[5/16/2020, 5:04:19 PM] [LgWebOsTv] Device: 192.168.15.143 3, get current Volume level successful: %s
[5/16/2020, 5:04:19 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge TV, get current Mute state successful: OFF

**Comment by grzegorz914** [comment]
Please update to 0.9.60 and test power state

**Comment by angyp** [comment]
No good. It's all over the place. If the TV is on when I restart homebridge the home app shows it as on and if I turn it off by remote it's reflected in the home app. However, if I turn it back on using the remote the app states it's off. If I restart home bridge with the TV off and I turn it on using the app that works but then I can't turn it off using the app and it shows as no response in the app.

**Comment by grzegorz914** [comment]
For me is working like a harm with 3 TV tested and all combinations ON/OFF from HomeKit app, CEC, or RC, always report correct state.

**Comment by angyp** [comment]
What version of homebridge are you running? Me 1.0.4. What should I try then?

**Comment by grzegorz914** [comment]
1.0.4

**Comment by grzegorz914** [comment]
are U disabled supportOldWebOs?

**Comment by angyp** [comment]
Yeah. Hey why if I have the name set to Lounge TV does it show up in the home app as "Lounge Television" but in the RC app it shows as "Lounge TV"
          "devices": [
                {
                    "name": "Lounge TV",
                    "host": "192.168.15.143",
                    "mac": "38:8c:50:5d:80:d0",
                    "volumeControl": true,
                    "switchInfoMenu": true,
                    "supportOldWebOs": false,
                    "inputs": [
                        {
                            "name": "Foxtel",
                            "reference": "com.webos.app.hdmi1",
                            "type": "HDMI"
                        },
                        {
                            "name": "Shield",
                            "reference": "com.webos.app.hdmi2",
                            "type": "HDMI"
                        },
                        {
                            "name": "Plex",
                            "reference": "cdp-30",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "YouTube",
                            "reference": "youtube.leanback.v4",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Netflix",
                            "reference": "netflix",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "Amazon Prime",
                            "reference": "amazon",
                            "type": "APPLICATION"
                        },
                        {
                            "name": "LiveTV",
                            "reference": "com.webos.app.livetv",
                            "type": "TUNER"
                        }
                    ]
                }
            ],
            "platform": "LgWebOsTv"
        }
    ],

**Comment by grzegorz914** [comment]
I don't know what, may be try remove the plugin and install again.

**Comment by angyp** [comment]
A complete rebuild is done. Deleted persist, accessories, and lgwebosTv directories. Still, the same behaviour. Time to move on to a different plugin or downgrade to 0.5.16 as I think that was about the best I have seen it.

**Comment by grzegorz914** [comment]
Enable debug and get again the log:

1. Enable TV from HomeKit app get log
2. Disable TV from homeKit app get log
3 Enable TV for RC get log
4 Disable TV from RC get log

**Comment by angyp** [comment]
Just downgraded to 0.5.16 and everything works perfectly. I will upgrade tomorrow and get you the logs your after but for now, I might just watch TV for now.
