### ISSUE TITLE
picture mode

### ISSUE THREAD

**Issue by RealNd** [grzegorz914/homebridge-lgwebos-tv#130]
how can I set the button to switch between picture mode?

**Comment by RealNd** [comment]
"pictureModeControl": true,
                    "pictureModes": [
                        {
                            "name": "norm",
                            "reference": "normal"
                        },
                        {
                            "name": "ec",
                            "reference": "eco"
                        }
                    ]

[12.06.2022, 22:22:10] [LgWebOsTv] Device: 192.168.68.129 Телевизор в спальне ReferenceError: response is not defined
    at On.setHandler (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:1018:163)
    at On.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1676:42)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:16)
    at On.Characteristic.handleSetRequest (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:824:38)
    at Accessory.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1810:29)
    at step (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:144:27)
    at Object.next (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:125:57)
    at /usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:118:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/lib/node_modules/homebridge/node_modules/tslib/tslib.js:114:16)
    at Accessory.handleCharacteristicWrite (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1528:38)
    at _loop_2 (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1677:12)
    at Accessory.handleSetCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:1516:17)
    at HAPServer.emit (events.js:400:28)
    at HAPServer.handleCharacteristics (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:911:12)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:385:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12), set Picture Mode error: %s

**Comment by RealNd** [comment]
with the help of another plugin, everything works. I want to use your plugin
