### ISSUE TITLE
Homebridge process ends unexpectedly 

### ISSUE THREAD

**Issue by pespinel** [grzegorz914/homebridge-lgwebos-tv#139]
Plugin version: 2.2.5
Homebridge version: 1.5.0
Homebridge UI version: 4.50.1

Logs: 
```
[26/09/2022, 19:51:39] [LgWebOsTv] Device: 192.168.1.10 LG C9, Specialized socket connection error: Error [ERR_STREAM_WRITE_AFTER_END]: write after end, reconnect in 6s.
[26/09/2022, 19:51:39] TypeError: specialClient.close is not a function
    at WebSocketConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/src/lgwebsocket.js:123:51)
    at WebSocketConnection.emit (node:events:527:28)
    at WebSocketConnection.handleSocketError (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:349:14)
    at Socket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
    at runNextTicks (node:internal/process/task_queues:65:3)
    at listOnTimeout (node:internal/timers:528:9)
    at processTimers (node:internal/timers:502:7)
[26/09/2022, 19:51:39] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[26/09/2022, 19:51:44] [HB Supervisor] Restarting Homebridge...
```

**Comment by grzegorz914** [comment]
One note, run this plugin as a Child bridge, this prevent restart HB.
