### ISSUE TITLE
Setting specific Live TV channels stopped working

### ISSUE THREAD

**Issue by North33** [grzegorz914/homebridge-lgwebos-tv#165]
Hello, I have a problem with controling the TV by setting specific Live TV channels (Homebridge 4.50.2 and LG webOS TV 2.9.0, but also 2.8.x and 2.7.x as I mention below). It worked perflectly fine a few weeks ago (and still works when I move back to LG webOS TV 2.6.7). 

My config:

```
  "devices": [
                {
                    "name": "LG OLED TV",
                    "host": "192.168.1.170",
                    "mac": "64:95:6C:F1:4C:29",
                    "getInputsFromDevice": false,
                    "filterSystemApps": false,
                    "buttons": [
                        {
                            "name": "Polsat News",
                            "mode": 1,
                            "reference": "1_50_5_0_17_237_1",
                            "displayType": 0
                        },
                        {
                            "name": "TVN 24",
                            "mode": 1,
                            "reference": "1_52_9_0_19_1011_1",
                            "displayType": 0
                        },
                        {
                            "name": "TVN",
                            "mode": 1,
                            "reference": "1_27_8_0_29_44_1",
                            "displayType": 0
                        },
                        {
                            "name": "Channel Up",
                            "mode": 2,
                            "command": "CHANNELUP",
                            "displayType": 0
                        },
                        {
                            "name": "Channel Down",
                            "mode": 2,
                            "command": "CHANNELDOWN",
                            "displayType": 0
                        }
                    ],
                    "sensorPower": false,
                    "sensorVolume": false,
                    "sensorMute": false,
                    "sensorInput": false,
                    "sensorChannel": false,
                    "sensorScreenOnOff": false,
                    "sensorScreenSaver": false,
                    "brightnessControl": false,
                    "backlightControl": false,
                    "contrastControl": false,
                    "colorControl": false,
                    "pictureModeControl": false,
                    "soundModeControl": false,
                    "enableDebugMode": true,
                    "disableLogInfo": false,
                    "disableLogDeviceInfo": false,
                    "turnScreenOnOff": false,
                    "sslWebSocket": false,
                    "enableMqtt": false,
                    "mqttDebug": false,
                    "mqttAuth": false
                }
            ],
```

I've run debug and here are the logs using buttons setting specific channels:

```
[26/03/2023, 23:15:30] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, set Channel Name: Polsat News, Reference: 1_50_5_0_17_237_1
[26/03/2023, 23:15:30] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Received message: {"type":"response","id":"6b1b021e0000","payload":{"returnValue":true,"id":"com.webos.app.livetv","sessionId":"Y29tLndlYm9zLmFwcC5saXZldHY="}}
[26/03/2023, 23:15:30] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Message Id: 6b1b021e0000, Data: {
  "returnValue": true,
  "id": "com.webos.app.livetv",
  "sessionId": "Y29tLndlYm9zLmFwcC5saXZldHY="
```

and nothing happens then. 

When I change channels using Channel Up oraz Channel Down buttons everything works fine. Here's an example:

```
[26/03/2023, 23:16:53] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, set Command Name: Channel Down, Reference: CHANNELDOWN
[26/03/2023, 23:16:53] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Received message: {"type":"response","id":"cccc10a70000","payload":{"channelId":"1_50_5_0_17_237_1","dualChannel":{"dualChannelId":null,"dualChannelTypeName":null,"dualChannelTypeId":255,"dualChannelNumber":null},"isScrambled":false,"channelTypeName":"Terrestrial Digital TV","isLocked":false,"isChannelChanged":false,"channelModeName":"Terrestrial","channelNumber":"5","isFineTuned":false,"channelTypeId":1,"isDescrambled":false,"isReplaceChannel":false,"isSkipped":false,"isHEVCChannel":false,"hybridtvType":null,"isInteractiveRestrictionChannel":false,"isInvisible":false,"favoriteGroup":null,"channelName":"159 Polsat News HD","channelModeId":0,"signalChannelId":"17_237_1"}}
[26/03/2023, 23:16:53] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Message Id: cccc10a70000, Data: {
  "channelId": "1_50_5_0_17_237_1",
  "dualChannel": {
    "dualChannelId": null,
    "dualChannelTypeName": null,
    "dualChannelTypeId": 255,
    "dualChannelNumber": null
  },
  "isScrambled": false,
  "channelTypeName": "Terrestrial Digital TV",
  "isLocked": false,
  "isChannelChanged": false,
  "channelModeName": "Terrestrial",
  "channelNumber": "5",
  "isFineTuned": false,
  "channelTypeId": 1,
  "isDescrambled": false,
  "isReplaceChannel": false,
  "isSkipped": false,
  "isHEVCChannel": false,
  "hybridtvType": null,
  "isInteractiveRestrictionChannel": false,
  "isInvisible": false,
  "favoriteGroup": null,
  "channelName": "159 Polsat News HD",
  "channelModeId": 0,
  "signalChannelId": "17_237_1"
```

Channel ID seems ok, I have also tried signalChannelID, channelName and channelNumber with no success.

Then I have moved back to **LG webOS TV v2.6.7**  and without changing a thing buttons started working again. I also checked **2.8.x** - it doesn't work and **2.7.x** - it doesn't work. Here's the logs from 2.6.7:

```
[26/03/2023, 23:41:07] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, set Channel name: Polsat News, reference: 1_50_5_0_17_237_1
[26/03/2023, 23:41:07] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Received message: {"type":"response","id":"0df0ce340000","payload":{"returnValue":true}}
[26/03/2023, 23:41:07] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Message Id: 0df0ce340000, Data: {
  "returnValue": true
}
[26/03/2023, 23:41:07] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Received message: {"type":"response","id":"198206ec0000","payload":{"channelId":"1_50_5_0_17_237_1","dualChannel":{"dualChannelId":null,"dualChannelTypeName":null,"dualChannelTypeId":255,"dualChannelNumber":null},"isScrambled":false,"channelTypeName":"Terrestrial Digital TV","isLocked":false,"isChannelChanged":false,"channelModeName":"Terrestrial","channelNumber":"5","isFineTuned":false,"channelTypeId":1,"isDescrambled":false,"isReplaceChannel":false,"isSkipped":false,"isHEVCChannel":false,"hybridtvType":null,"isInteractiveRestrictionChannel":false,"isInvisible":false,"favoriteGroup":null,"channelName":"159 Polsat News HD","channelModeId":0,"signalChannelId":"17_237_1"}}
[26/03/2023, 23:41:07] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Message Id: 198206ec0000, Data: {
  "channelId": "1_50_5_0_17_237_1",
  "dualChannel": {
    "dualChannelId": null,
    "dualChannelTypeName": null,
    "dualChannelTypeId": 255,
    "dualChannelNumber": null
  },
  "isScrambled": false,
  "channelTypeName": "Terrestrial Digital TV",
  "isLocked": false,
  "isChannelChanged": false,
  "channelModeName": "Terrestrial",
  "channelNumber": "5",
  "isFineTuned": false,
  "channelTypeId": 1,
  "isDescrambled": false,
  "isReplaceChannel": false,
  "isSkipped": false,
  "isHEVCChannel": false,
  "hybridtvType": null,
  "isInteractiveRestrictionChannel": false,
  "isInvisible": false,
  "favoriteGroup": null,
  "channelName": "159 Polsat News HD",
  "channelModeId": 0,
  "signalChannelId": "17_237_1"
}
```

**Comment by grzegorz914** [comment]
try 2.9.1-beta.o and let me know

**Comment by North33** [comment]
I installed 2.9.1-beta.5, is it OK? I couldn't find 2.9.1-beta.1 in Homebridge (screen below).

At 2.9.1-beta.5 the whole LG webOS TV keeps restarting, logs below.

```
[27/03/2023, 10:25:04] [homebridge-lgwebos-tv] Restarting Process...
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Launched child bridge with PID 5712
[27/03/2023, 10:25:05] Registering platform 'homebridge-lgwebos-tv.LgWebOsTv'
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Loaded homebridge-lgwebos-tv v2.9.1-beta.5 child bridge successfully
[27/03/2023, 10:25:05] Loaded 0 cached accessories from cachedAccessories.0E2C9A523D82.
[27/03/2023, 10:25:05] Homebridge v1.6.0 (HAP v0.11.0) (homebridge-lgwebos-tv) is running on port 50685.
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Socked connected.
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Received message: {"type":"registered","id":"ba13ded10000","payload":{"client-key":"fa7ac0d8639520a626acdde14d5d2b5e"}}
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Message Id: ba13ded10000, Data: {
  "client-key": "fa7ac0d8639520a626acdde14d5d2b5e"
}
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Start pairing: {
  "client-key": "fa7ac0d8639520a626acdde14d5d2b5e"
}
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Received message: {"type":"response","id":"71b460730000","payload":{"socketPath":"ws://192.168.1.170:3000/resources/a9ebb8862630e24691390128baccba0ee8be7b51/netinput.pointer.sock","returnValue":true}}
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Message Id: 71b460730000, Data: {
  "socketPath": "ws://192.168.1.170:3000/resources/a9ebb8862630e24691390128baccba0ee8be7b51/netinput.pointer.sock",
  "returnValue": true
}
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Socket Path: {
  "socketPath": "ws://192.168.1.170:3000/resources/a9ebb8862630e24691390128baccba0ee8be7b51/netinput.pointer.sock",
  "returnValue": true
}
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Received message: {"type":"response","id":"decc2e290000","payload":{"returnValue":true,"features":{"dvr":false},"receiverType":"DVB","modelName":"OLED55GX3LA","programMode":true}}
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Message Id: decc2e290000, Data: {
  "returnValue": true,
  "features": {
    "dvr": false
  },
  "receiverType": "DVB",
  "modelName": "OLED55GX3LA",
  "programMode": true
}
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: System Info: {
  "returnValue": true,
  "features": {
    "dvr": false
  },
  "receiverType": "DVB",
  "modelName": "OLED55GX3LA",
  "programMode": true
}
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Specialized socket connected.
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Received message: {"type":"response","id":"1c8fdf670000","payload":{"returnValue":true,"product_name":"webOSTV 5.0","model_name":"HE_DTV_W20O_AFABABAA","sw_type":"FIRMWARE","major_ver":"04","minor_ver":"40.70","country":"PL","country_group":"EU","device_id":"64:95:6c:f1:4c:29","auth_flag":"N","ignore_disable":"N","eco_info":"01","config_key":"00","language_code":"pl-PL"}}
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Message Id: 1c8fdf670000, Data: {
  "returnValue": true,
  "product_name": "webOSTV 5.0",
  "model_name": "HE_DTV_W20O_AFABABAA",
  "sw_type": "FIRMWARE",
  "major_ver": "04",
  "minor_ver": "40.70",
  "country": "PL",
  "country_group": "EU",
  "device_id": "64:95:6c:f1:4c:29",
  "auth_flag": "N",
  "ignore_disable": "N",
  "eco_info": "01",
  "config_key": "00",
  "language_code": "pl-PL"
}
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, debug: Software Info: {
  "returnValue": true,
  "product_name": "webOSTV 5.0",
  "model_name": "HE_DTV_W20O_AFABABAA",
  "sw_type": "FIRMWARE",
  "major_ver": "04",
  "minor_ver": "40.70",
  "country": "PL",
  "country_group": "EU",
  "device_id": "64:95:6c:f1:4c:29",
  "auth_flag": "N",
  "ignore_disable": "N",
  "eco_info": "01",
  "config_key": "00",
  "language_code": "pl-PL"
}
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Device: 192.168.1.170 LG OLED TV, Connected.

/var/lib/homebridge/node_modules/homebridge-lgwebos-tv/src/lgwebsocket.js:153
                        this.emit('deviceInfo', modelName, productName, serialNumber, firmwareRevision, webOS);
                                                ^
ReferenceError: Cannot access 'modelName' before initialization
    at WebSocket.<anonymous> (/var/lib/homebridge/node_modules/homebridge-lgwebos-tv/src/lgwebsocket.js:153:49)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/var/lib/homebridge/node_modules/homebridge-lgwebos-tv/node_modules/ws/lib/websocket.js:1184:20)
    at Receiver.emit (node:events:527:28)
    at Receiver.dataMessage (/var/lib/homebridge/node_modules/homebridge-lgwebos-tv/node_modules/ws/lib/receiver.js:541:14)
    at Receiver.getData (/var/lib/homebridge/node_modules/homebridge-lgwebos-tv/node_modules/ws/lib/receiver.js:459:17)
    at Receiver.startLoop (/var/lib/homebridge/node_modules/homebridge-lgwebos-tv/node_modules/ws/lib/receiver.js:158:22)
    at Receiver._write (/var/lib/homebridge/node_modules/homebridge-lgwebos-tv/node_modules/ws/lib/receiver.js:84:10)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Child bridge process ended
[27/03/2023, 10:25:05] [homebridge-lgwebos-tv] Process Ended. Code: 1, Signal: null
```
<img width="608" alt="Zrzut ekranu 2023-03-27 o 10 22 50" src="https://user-images.githubusercontent.com/129008273/227885354-3553aa3b-ce90-4050-a9a9-e8a37d147a2d.png">

**Comment by grzegorz914** [comment]
ups, try beta.6

**Comment by North33** [comment]
Now it works, setting specific channels is back:) Thank you very much!
