### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'enable')

### ISSUE THREAD

**Issue by pasqualito79** [grzegorz914/homebridge-lgwebos-tv#219]
with 3.0.0 and also 3.0.1 the plugin also crashes with a similar error than the ones you already fixed:

[8/15/2024, 8:05:04 PM] TypeError: Cannot read properties of undefined (reading 'enable')
at LgWebOsSocket. (/volume1/homebridge/node_modules/homebridge-lgwebos-tv/src/lgwebosdevice.js:583:55)
at LgWebOsSocket.emit (node:events:514:28)
at LgWebOsSocket.prepareAccessory (/volume1/homebridge/node_modules/homebridge-lgwebos-tv/src/lgwebossocket.js:835:18)
at Timeout._onTimeout (/volume1/homebridge/node_modules/homebridge-lgwebos-tv/src/lgwebossocket.js:754:95)
[8/15/2024, 8:05:04 PM] Got SIGTERM, shutting down Homebridge...

**Comment by grzegorz914** [comment]
this was fixed with 3.0.2
