### ISSUE TITLE
Version 0.8.7 bug

### ISSUE THREAD

**Issue by Lui5Jacint0** [grzegorz914/homebridge-lgwebos-tv#22]
11/05/2020, 15:47:34 ReferenceError: homebridge is not defined
    at Object.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:9:24)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Plugin.load (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/plugin.js:44:35)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:152:24
    at Array.forEach (<anonymous>)
11/05/2020, 15:47:35 The requested platform "LgWebOsTv" was not registered by any plugin.
11/05/2020, 15:47:35 Your config.json is requesting the platform "LgWebOsTv" which has not been published by any installed plugins.

This error occurred after installing the latest update.

Could you help?

**Comment by grzegorz914** [comment]
Fixed , make update again.

**Comment by Lui5Jacint0** [comment]
Unfortunately i don't have any update available.

**Comment by grzegorz914** [comment]
0.8.9 is the latest

**Comment by Lui5Jacint0** [comment]
![Captura de ecrã 2020-05-11, às 16 26 08](https://user-images.githubusercontent.com/930892/81585926-5a78b080-93a4-11ea-99c3-76ae67a7bed7.png)

It's not available yet on HOOBS

**Comment by grzegorz914** [comment]
I publish on npm,
![B867A32C-2CA2-47B8-B603-E93883F60647](https://user-images.githubusercontent.com/28867813/81586236-83ee0800-93b5-11ea-9e7a-4fa21d00759a.png)

**Comment by donavanbecker** [comment]
@Lui5Jacint0 latest version is available on homebridge, I have just tested it out. To get the latest i would recommend installing regular homebridge.

**Comment by Lui5Jacint0** [comment]
I've done a clean install with version 0.8.9, plugin running with no errors, but unable to add to homekit.

**Comment by grzegorz914** [comment]
That is Hoobs,
Rename the device restart homebridge and try add it again.

**Comment by Lui5Jacint0** [comment]
Working fine! thanks for the help!
