### ISSUE TITLE
Version 3.1.6 crashes on startup only when TV is off

### ISSUE THREAD

**Issue by vfontes** [grzegorz914/homebridge-lgwebos-tv#226]
I was only able to reproduce this in 3.1.6; it seems like 3.1.1 and below are not affected.

Here's the debug logs when the TV is off and the plugin starts:

```
[9/9/2024, 10:39:48 AM] [homebridge-lgwebos-tv] Process Ended. Code: 1, Signal: null
[9/9/2024, 10:39:55 AM] [homebridge-lgwebos-tv] Restarting Process...
[9/9/2024, 10:39:55 AM] [homebridge-lgwebos-tv] Launched child bridge with PID 4873
[9/9/2024, 10:39:56 AM] Registering platform 'homebridge-lgwebos-tv.LgWebOsTv'
[9/9/2024, 10:39:56 AM] [homebridge-lgwebos-tv] Loaded homebridge-lgwebos-tv v3.1.6 child bridge successfully
[9/9/2024, 10:39:56 AM] Loaded 0 cached accessories from cachedAccessories.0EC62BC21CCF.
[9/9/2024, 10:39:56 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, did finish launching.
[9/9/2024, 10:39:56 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, Config: {
  "name": "Sala TV",
  "host": "192.168.1.236",
  "mac": "20:17:42:3b:2d:9f",
  "getInputsFromDevice": true,
  "disableLoadDefaultInputs": false,
  "filterSystemApps": true,
  "inputsDisplayOrder": 0,
  "sensorPower": false,
  "sensorPixelRefresh": false,
  "sensorVolume": false,
  "sensorMute": false,
  "sensorInput": false,
  "sensorChannel": false,
  "sensorSoundMode": false,
  "sensorSoundOutput": false,
  "sensorPictureMode": false,
  "sensorScreenOnOff": false,
  "sensorScreenSaver": false,
  "turnScreenOnOff": false,
  "turnScreenSaverOnOff": false,
  "brightnessControl": false,
  "backlightControl": false,
  "contrastControl": false,
  "colorControl": false,
  "pictureModeControl": false,
  "volumeControlNamePrefix": false,
  "volumeControl": 0,
  "soundModeControl": false,
  "soundOutputControl": true,
  "soundOutputs": [
    {
      "name": "ARC",
      "reference": "external_arc",
      "displayType": 2
    }
  ],
  "serviceMenu": false,
  "sslWebSocket": false,
  "disableTvService": false,
  "ezAdjustMenu": false,
  "infoButtonCommand": "MENU",
  "enableDebugMode": true,
  "disableLogInfo": false,
  "disableLogDeviceInfo": false,
  "restFul": {
    "enable": false,
    "debug": false
  },
  "mqtt": {
    "enable": false,
    "debug": false,
    "auth": false,
    "passwd": "removed"
  }
}
[9/9/2024, 10:39:56 AM] Homebridge v1.8.4 (HAP v0.12.2) (homebridge-lgwebos-tv) is running on port 34781.
[9/9/2024, 10:39:56 AM] 

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[9/9/2024, 10:39:56 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Read data: {
  "type": "Buffer",
  "data": [
    54,
    97,
    101,
    99,
    100,
    97,
    99,
    100,
    99,
    102,
    52,
    50,
    50,
    102,
    99,
    52,
    97,
    48,
    54,
    97,
    102,
    100,
    97,
    57,
    101,
    48,
    101,
    51,
    99,
    53,
    98,
    52
  ]
}
[9/9/2024, 10:39:56 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Connecting to socket.
[9/9/2024, 10:39:59 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Socket connect error: Error: connect EHOSTUNREACH 192.168.1.236:3000.
[9/9/2024, 10:39:59 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, Power: OFF
[9/9/2024, 10:39:59 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, Volume: 0%
[9/9/2024, 10:39:59 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, Mute: ON
[9/9/2024, 10:39:59 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, Brightness: 0%
[9/9/2024, 10:39:59 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, Backlight: 0%
[9/9/2024, 10:39:59 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, Contrast: 0%
[9/9/2024, 10:39:59 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, Color: 0%
[9/9/2024, 10:39:59 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, Picture Mode: Unknown
[9/9/2024, 10:39:59 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, Sound Mode: Unknown

/var/lib/homebridge/node_modules/homebridge-lgwebos-tv/src/lgwebosdevice.js:550
                                .updateCharacteristic(Characteristic.On, state);
                                 ^
TypeError: Cannot read properties of undefined (reading 'updateCharacteristic')
    at LgWebOsSocket.<anonymous> (/var/lib/homebridge/node_modules/homebridge-lgwebos-tv/src/lgwebosdevice.js:550:34)
    at LgWebOsSocket.emit (node:events:519:28)
    at WebSocket.<anonymous> (/var/lib/homebridge/node_modules/homebridge-lgwebos-tv/src/lgwebossocket.js:770:18)
    at WebSocket.emit (node:events:519:28)
    at WebSocket.<anonymous> (/var/lib/homebridge/node_modules/homebridge-lgwebos-tv/src/lgwebossocket.js:748:20)
    at WebSocket.emit (node:events:519:28)
    at emitErrorAndClose (/var/lib/homebridge/node_modules/homebridge-lgwebos-tv/node_modules/ws/lib/websocket.js:1041:13)
    at ClientRequest.<anonymous> (/var/lib/homebridge/node_modules/homebridge-lgwebos-tv/node_modules/ws/lib/websocket.js:881:5)
    at ClientRequest.emit (node:events:519:28)
    at emitErrorEvent (node:_http_client:108:11)
[9/9/2024, 10:39:59 AM] [homebridge-lgwebos-tv] Child bridge process ended
[9/9/2024, 10:39:59 AM] [homebridge-lgwebos-tv] Process Ended. Code: 1, Signal: null
[9/9/2024, 10:40:06 AM] [homebridge-lgwebos-tv] Restarting Process...
```

**Comment by vfontes** [comment]
Once the TV is on, it starts correctly:

```[9/9/2024, 10:46:38 AM] [homebridge-lgwebos-tv] Restarting child bridge...
[9/9/2024, 10:46:38 AM] Got SIGTERM, shutting down child bridge process...
[9/9/2024, 10:46:38 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Socked send heartbeat.
[9/9/2024, 10:46:38 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Socked received heartbeat.
[9/9/2024, 10:46:43 AM] [homebridge-lgwebos-tv] Child bridge process ended
[9/9/2024, 10:46:43 AM] [homebridge-lgwebos-tv] Process Ended. Code: 143, Signal: null
[9/9/2024, 10:46:50 AM] [homebridge-lgwebos-tv] Restarting Process...
[9/9/2024, 10:46:50 AM] [homebridge-lgwebos-tv] Launched child bridge with PID 5163
[9/9/2024, 10:46:50 AM] Registering platform 'homebridge-lgwebos-tv.LgWebOsTv'
[9/9/2024, 10:46:50 AM] [homebridge-lgwebos-tv] Loaded homebridge-lgwebos-tv v3.1.1 child bridge successfully
[9/9/2024, 10:46:50 AM] Loaded 0 cached accessories from cachedAccessories.0EC62BC21CCF.
[9/9/2024, 10:46:50 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, did finish launching.
[9/9/2024, 10:46:50 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, Config: {
  "name": "Sala TV",
  "host": "192.168.1.236",
  "mac": "20:17:42:3b:2d:9f",
  "getInputsFromDevice": true,
  "disableLoadDefaultInputs": false,
  "filterSystemApps": true,
  "inputsDisplayOrder": 0,
  "sensorPower": false,
  "sensorPixelRefresh": false,
  "sensorVolume": false,
  "sensorMute": false,
  "sensorInput": false,
  "sensorChannel": false,
  "sensorSoundMode": false,
  "sensorSoundOutput": false,
  "sensorPictureMode": false,
  "sensorScreenOnOff": false,
  "sensorScreenSaver": false,
  "turnScreenOnOff": false,
  "turnScreenSaverOnOff": false,
  "brightnessControl": false,
  "backlightControl": false,
  "contrastControl": false,
  "colorControl": false,
  "pictureModeControl": false,
  "volumeControlNamePrefix": false,
  "volumeControl": 0,
  "soundModeControl": false,
  "soundOutputControl": true,
  "soundOutputs": [
    {
      "name": "ARC",
      "reference": "external_arc",
      "displayType": 2
    }
  ],
  "serviceMenu": false,
  "sslWebSocket": false,
  "disableTvService": false,
  "ezAdjustMenu": false,
  "infoButtonCommand": "MENU",
  "enableDebugMode": true,
  "disableLogInfo": false,
  "disableLogDeviceInfo": false,
  "restFul": {
    "enable": false,
    "debug": false
  },
  "mqtt": {
    "enable": false,
    "debug": false,
    "auth": false,
    "passwd": "removed"
  }
}
[9/9/2024, 10:46:50 AM] Homebridge v1.8.4 (HAP v0.12.2) (homebridge-lgwebos-tv) is running on port 33489.
[9/9/2024, 10:46:50 AM]

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[9/9/2024, 10:46:53 AM] [Weather] Porto Alegre Temperature: Current Temperature: set to 21.2°C (from 21.7°C)
[9/9/2024, 10:46:53 AM] [Weather] Porto Alegre Humidity: Current Relative Humidity: set to 87% (from 86%)
[9/9/2024, 10:46:53 AM] [Weather] Porto Alegre Weather: Apparent Temperature: set to 21.6°C (from 22.1°C)
[9/9/2024, 10:46:53 AM] [Weather] Porto Alegre Weather: Dew Point: set to 18.91°C (from 19.22°C)
[9/9/2024, 10:46:53 AM] [Weather] Porto Alegre Weather: Observation Time: set to "Mon Sep 09 2024 10:46:53" (from "Mon Sep 09 2024 10:36:09")
[9/9/2024, 10:47:00 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Plugin send heartbeat to TV.
[9/9/2024, 10:47:00 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Plugin received heartbeat from TV.
[9/9/2024, 10:47:00 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Connecting to socket.
[9/9/2024, 10:47:00 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Socked connected.
[9/9/2024, 10:47:00 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Socket send: {"id":"b7e08ea80001","type":"register","payload":{"forcePairing":false,"pairingType":"PROMPT","manifest":{"manifestVersion":1,"appVersion":"1.1","signed":{"created":"20140509","appId":"com.lge.test","vendorId":"com.lge","localizedAppNames":{"":"LG Remote App","ko-KR":"리모컨 앱","zxx-XX":"ЛГ Rэмotэ AПП"},"localizedVendorNames":{"":"LG Electronics"},"permissions":["TEST_SECURE","CONTROL_INPUT_TEXT","CONTROL_MOUSE_AND_KEYBOARD","READ_INSTALLED_APPS","READ_LGE_SDX","READ_NOTIFICATIONS","SEARCH","WRITE_SETTINGS","WRITE_NOTIFICATION_ALERT","CONTROL_POWER","READ_CURRENT_CHANNEL","READ_RUNNING_APPS","READ_UPDATE_INFO","UPDATE_FROM_REMOTE_APP","READ_LGE_TV_INPUT_EVENTS","READ_TV_CURRENT_TIME"],"serial":"2f930e2d2cfe083771f68e4fe7bb07"},"permissions":["LAUNCH","LAUNCH_WEBAPP","APP_TO_APP","CLOSE","TEST_OPEN","TEST_PROTECTED","CONTROL_AUDIO","CONTROL_DISPLAY","CONTROL_INPUT_JOYSTICK","CONTROL_INPUT_MEDIA_RECORDING","CONTROL_INPUT_MEDIA_PLAYBACK","CONTROL_INPUT_TV","CONTROL_POWER","CONTROL_TV_SCREEN","CONTROL_TV_STANBY","CONTROL_FAVORITE_GROUP","CONTROL_USER_INFO","CONTROL_BLUETOOTH","CONTROL_TIMER_INFO","CONTROL_RECORDING","CONTROL_BOX_CHANNEL","CONTROL_CHANNEL_BLOCK","CONTROL_CHANNEL_GROUP","CONTROL_TV_POWER","CONTROL_WOL","READ_APP_STATUS","READ_CURRENT_CHANNEL","READ_INPUT_DEVICE_LIST","READ_NETWORK_STATE","READ_RUNNING_APPS","READ_TV_CHANNEL_LIST","READ_POWER_STATE","READ_COUNTRY_INFO","READ_SETTINGS","READ_RECORDING_STATE","READ_RECORDING_LIST","READ_RECORDING_SCHEDULE","READ_STORAGE_DEVICE_LIST","READ_TV_PROGRAM_INFO","READ_TV_ACR_AUTH_TOKEN","READ_TV_CONTENT_STATE","READ_TV_CURRENT_TIME","WRITE_NOTIFICATION_TOAST","WRITE_RECORDING_LIST","WRITE_RECORDING_SCHEDULE","CHECK_BLUETOOTH_DEVICE","STB_INTERNAL_CONNECTION","ADD_LAUNCHER_CHANNEL","SCAN_TV_CHANNELS","SET_CHANNEL_SKIP","RELEASE_CHANNEL_SKIP","DELETE_SELECT_CHANNEL"],"signatures":[{"signatureVersion":1,"signature":"eyJhbGdvcml0aG0iOiJSU0EtU0hBMjU2Iiwia2V5SWQiOiJ0ZXN0LXNpZ25pbmctY2VydCIsInNpZ25hdHVyZVZlcnNpb24iOjF9.hrVRgjCwXVvE2OOSpDZ58hR+59aFNwYDyjQgKk3auukd7pcegmE2CzPCa0bJ0ZsRAcKkCTJrWo5iDzNhMBWRyaMOv5zWSrthlf7G128qvIlpMT0YNY+n/FaOHE73uLrS/g7swl3/qH/BGFG2Hu4RlL48eb3lLKqTt2xKHdCs6Cd4RMfJPYnzgvI4BNrFUKsjkcu+WD4OO2A27Pq1n50cMchmcaXadJhGrOqH5YmHdOCj5NSHzJYrsW0HPlpuAx/ECMeIZYDh6RMqaFM2DXzdKX9NmmyqzJ3o/0lkk/N97gfVRLW5hA29yeAwaCViZNCP8iC9aO0q9fQojoa7NQnAtw=="}]},"client-key":"6aecdacdcf422fc4a06afda9e0e3c5b4"}}
[9/9/2024, 10:47:00 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Registered to TV with key: 6aecdacdcf422fc4a06afda9e0e3c5b4
[9/9/2024, 10:47:02 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Socket send: {"id":"90138d600002","type":"request","uri":"ssap://com.webos.service.networkinput/getPointerInputSocket","payload":{}}
[9/9/2024, 10:47:02 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Connecting to specjalized socket.
[9/9/2024, 10:47:02 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Specialized socket connected, path: ws://192.168.1.236:3000/resources/478446421c93b113f17e37c9ea7163d03c9d630a/netinput.pointer.sock.
[9/9/2024, 10:47:02 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Socket send: {"id":"2f7e6c100003","type":"request","uri":"ssap://system/getSystemInfo","payload":{}}
[9/9/2024, 10:47:02 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: System info: {
  "returnValue": true,
  "features": {
    "3d": false,
    "dvr": true
  },
  "receiverType": "atsc",
  "modelName": "OLED55C9PSA",
  "programMode": "false"
}

```

**Comment by vfontes** [comment]
Once the TV is on, it starts correctly:

```[9/9/2024, 10:46:38 AM] [homebridge-lgwebos-tv] Restarting child bridge...
[9/9/2024, 10:46:38 AM] Got SIGTERM, shutting down child bridge process...
[9/9/2024, 10:46:38 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Socked send heartbeat.
[9/9/2024, 10:46:38 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Socked received heartbeat.
[9/9/2024, 10:46:43 AM] [homebridge-lgwebos-tv] Child bridge process ended
[9/9/2024, 10:46:43 AM] [homebridge-lgwebos-tv] Process Ended. Code: 143, Signal: null
[9/9/2024, 10:46:50 AM] [homebridge-lgwebos-tv] Restarting Process...
[9/9/2024, 10:46:50 AM] [homebridge-lgwebos-tv] Launched child bridge with PID 5163
[9/9/2024, 10:46:50 AM] Registering platform 'homebridge-lgwebos-tv.LgWebOsTv'
[9/9/2024, 10:46:50 AM] [homebridge-lgwebos-tv] Loaded homebridge-lgwebos-tv v3.1.1 child bridge successfully
[9/9/2024, 10:46:50 AM] Loaded 0 cached accessories from cachedAccessories.0EC62BC21CCF.
[9/9/2024, 10:46:50 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, did finish launching.
[9/9/2024, 10:46:50 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, Config: {
  "name": "Sala TV",
  "host": "192.168.1.236",
  "mac": "20:17:42:3b:2d:9f",
  "getInputsFromDevice": true,
  "disableLoadDefaultInputs": false,
  "filterSystemApps": true,
  "inputsDisplayOrder": 0,
  "sensorPower": false,
  "sensorPixelRefresh": false,
  "sensorVolume": false,
  "sensorMute": false,
  "sensorInput": false,
  "sensorChannel": false,
  "sensorSoundMode": false,
  "sensorSoundOutput": false,
  "sensorPictureMode": false,
  "sensorScreenOnOff": false,
  "sensorScreenSaver": false,
  "turnScreenOnOff": false,
  "turnScreenSaverOnOff": false,
  "brightnessControl": false,
  "backlightControl": false,
  "contrastControl": false,
  "colorControl": false,
  "pictureModeControl": false,
  "volumeControlNamePrefix": false,
  "volumeControl": 0,
  "soundModeControl": false,
  "soundOutputControl": true,
  "soundOutputs": [
    {
      "name": "ARC",
      "reference": "external_arc",
      "displayType": 2
    }
  ],
  "serviceMenu": false,
  "sslWebSocket": false,
  "disableTvService": false,
  "ezAdjustMenu": false,
  "infoButtonCommand": "MENU",
  "enableDebugMode": true,
  "disableLogInfo": false,
  "disableLogDeviceInfo": false,
  "restFul": {
    "enable": false,
    "debug": false
  },
  "mqtt": {
    "enable": false,
    "debug": false,
    "auth": false,
    "passwd": "removed"
  }
}
[9/9/2024, 10:46:50 AM] Homebridge v1.8.4 (HAP v0.12.2) (homebridge-lgwebos-tv) is running on port 33489.
[9/9/2024, 10:46:50 AM]

NOTICE TO USERS AND PLUGIN DEVELOPERS
> Homebridge 2.0 is on the way and brings some breaking changes to existing plugins.
> Please visit the following link to learn more about the changes and how to prepare:
> https://github.com/homebridge/homebridge/wiki/Updating-To-Homebridge-v2.0

[9/9/2024, 10:46:53 AM] [Weather] Porto Alegre Temperature: Current Temperature: set to 21.2°C (from 21.7°C)
[9/9/2024, 10:46:53 AM] [Weather] Porto Alegre Humidity: Current Relative Humidity: set to 87% (from 86%)
[9/9/2024, 10:46:53 AM] [Weather] Porto Alegre Weather: Apparent Temperature: set to 21.6°C (from 22.1°C)
[9/9/2024, 10:46:53 AM] [Weather] Porto Alegre Weather: Dew Point: set to 18.91°C (from 19.22°C)
[9/9/2024, 10:46:53 AM] [Weather] Porto Alegre Weather: Observation Time: set to "Mon Sep 09 2024 10:46:53" (from "Mon Sep 09 2024 10:36:09")
[9/9/2024, 10:47:00 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Plugin send heartbeat to TV.
[9/9/2024, 10:47:00 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Plugin received heartbeat from TV.
[9/9/2024, 10:47:00 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Connecting to socket.
[9/9/2024, 10:47:00 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Socked connected.
[9/9/2024, 10:47:00 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Socket send: {"id":"b7e08ea80001","type":"register","payload":{"forcePairing":false,"pairingType":"PROMPT","manifest":{"manifestVersion":1,"appVersion":"1.1","signed":{"created":"20140509","appId":"com.lge.test","vendorId":"com.lge","localizedAppNames":{"":"LG Remote App","ko-KR":"리모컨 앱","zxx-XX":"ЛГ Rэмotэ AПП"},"localizedVendorNames":{"":"LG Electronics"},"permissions":["TEST_SECURE","CONTROL_INPUT_TEXT","CONTROL_MOUSE_AND_KEYBOARD","READ_INSTALLED_APPS","READ_LGE_SDX","READ_NOTIFICATIONS","SEARCH","WRITE_SETTINGS","WRITE_NOTIFICATION_ALERT","CONTROL_POWER","READ_CURRENT_CHANNEL","READ_RUNNING_APPS","READ_UPDATE_INFO","UPDATE_FROM_REMOTE_APP","READ_LGE_TV_INPUT_EVENTS","READ_TV_CURRENT_TIME"],"serial":"2f930e2d2cfe083771f68e4fe7bb07"},"permissions":["LAUNCH","LAUNCH_WEBAPP","APP_TO_APP","CLOSE","TEST_OPEN","TEST_PROTECTED","CONTROL_AUDIO","CONTROL_DISPLAY","CONTROL_INPUT_JOYSTICK","CONTROL_INPUT_MEDIA_RECORDING","CONTROL_INPUT_MEDIA_PLAYBACK","CONTROL_INPUT_TV","CONTROL_POWER","CONTROL_TV_SCREEN","CONTROL_TV_STANBY","CONTROL_FAVORITE_GROUP","CONTROL_USER_INFO","CONTROL_BLUETOOTH","CONTROL_TIMER_INFO","CONTROL_RECORDING","CONTROL_BOX_CHANNEL","CONTROL_CHANNEL_BLOCK","CONTROL_CHANNEL_GROUP","CONTROL_TV_POWER","CONTROL_WOL","READ_APP_STATUS","READ_CURRENT_CHANNEL","READ_INPUT_DEVICE_LIST","READ_NETWORK_STATE","READ_RUNNING_APPS","READ_TV_CHANNEL_LIST","READ_POWER_STATE","READ_COUNTRY_INFO","READ_SETTINGS","READ_RECORDING_STATE","READ_RECORDING_LIST","READ_RECORDING_SCHEDULE","READ_STORAGE_DEVICE_LIST","READ_TV_PROGRAM_INFO","READ_TV_ACR_AUTH_TOKEN","READ_TV_CONTENT_STATE","READ_TV_CURRENT_TIME","WRITE_NOTIFICATION_TOAST","WRITE_RECORDING_LIST","WRITE_RECORDING_SCHEDULE","CHECK_BLUETOOTH_DEVICE","STB_INTERNAL_CONNECTION","ADD_LAUNCHER_CHANNEL","SCAN_TV_CHANNELS","SET_CHANNEL_SKIP","RELEASE_CHANNEL_SKIP","DELETE_SELECT_CHANNEL"],"signatures":[{"signatureVersion":1,"signature":"eyJhbGdvcml0aG0iOiJSU0EtU0hBMjU2Iiwia2V5SWQiOiJ0ZXN0LXNpZ25pbmctY2VydCIsInNpZ25hdHVyZVZlcnNpb24iOjF9.hrVRgjCwXVvE2OOSpDZ58hR+59aFNwYDyjQgKk3auukd7pcegmE2CzPCa0bJ0ZsRAcKkCTJrWo5iDzNhMBWRyaMOv5zWSrthlf7G128qvIlpMT0YNY+n/FaOHE73uLrS/g7swl3/qH/BGFG2Hu4RlL48eb3lLKqTt2xKHdCs6Cd4RMfJPYnzgvI4BNrFUKsjkcu+WD4OO2A27Pq1n50cMchmcaXadJhGrOqH5YmHdOCj5NSHzJYrsW0HPlpuAx/ECMeIZYDh6RMqaFM2DXzdKX9NmmyqzJ3o/0lkk/N97gfVRLW5hA29yeAwaCViZNCP8iC9aO0q9fQojoa7NQnAtw=="}]},"client-key":"6aecdacdcf422fc4a06afda9e0e3c5b4"}}
[9/9/2024, 10:47:00 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Registered to TV with key: 6aecdacdcf422fc4a06afda9e0e3c5b4
[9/9/2024, 10:47:02 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Socket send: {"id":"90138d600002","type":"request","uri":"ssap://com.webos.service.networkinput/getPointerInputSocket","payload":{}}
[9/9/2024, 10:47:02 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Connecting to specjalized socket.
[9/9/2024, 10:47:02 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Specialized socket connected, path: ws://192.168.1.236:3000/resources/478446421c93b113f17e37c9ea7163d03c9d630a/netinput.pointer.sock.
[9/9/2024, 10:47:02 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: Socket send: {"id":"2f7e6c100003","type":"request","uri":"ssap://system/getSystemInfo","payload":{}}
[9/9/2024, 10:47:02 AM] [homebridge-lgwebos-tv] Device: 192.168.1.236 Sala TV, debug: System info: {
  "returnValue": true,
  "features": {
    "3d": false,
    "dvr": true
  },
  "receiverType": "atsc",
  "modelName": "OLED55C9PSA",
  "programMode": "false"
}

```
