### ISSUE TITLE
Screensaver changes powerstate to OFF

### ISSUE THREAD

**Issue by HollowCanine** [grzegorz914/homebridge-lgwebos-tv#29]
Every time the fireworks screensaver comes on the powerstate switches to OFF and the accessory won't work until homebridge is restarted.

**TV**: OLED55C8PUA (webOSTV 4.0 / Firmware: 10.45)
iOS version: 13.5
**Homebridge** version: 1.1.0 
**Plugins** versions: 
- homebridge-config-ui-x v4.20.0
- homebridge-lgwebos-tv v0.10.58

**Comment by grzegorz914** [comment]
Hi,
can U post the log in debug mode if this happens?

**Comment by HollowCanine** [comment]
[5/23/2020, 15:51:46] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Volume level: 0
[5/23/2020, 15:51:46] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Channel data: { returnValue: false, errorCode: -1000, errorText: 'internal error' }
[5/23/2020, 15:51:46] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Channel successful: undefined, undefined, undefined
[5/23/2020, 15:51:48] [LgWebOsTv] Device: 172.16.1.61 LG TV, requesting Device state.
[5/23/2020, 15:51:48] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current App state data: { appId: 'netflix', returnValue: true, windowId: '', processId: '' }
[5/23/2020, 15:51:48] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Input successful: Netflix netflix
[5/23/2020, 15:51:48] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Power state data: { returnValue: true, state: 'Active' }
[5/23/2020, 15:51:48] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Power state successful: ON
[5/23/2020, 15:51:48] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Audio state data: {
  returnValue: true,
  scenario: 'mastervolume_ext_speaker_arc',
  volume: 0,
  muted: false
}
[5/23/2020, 15:51:48] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Mute state: OFF
[5/23/2020, 15:51:48] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Volume level: 0
[5/23/2020, 15:51:48] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Channel data: { returnValue: false, errorCode: -1000, errorText: 'internal error' }
[5/23/2020, 15:51:48] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Channel successful: undefined, undefined, undefined
[5/23/2020, 15:51:50] [LgWebOsTv] Device: 172.16.1.61 LG TV, requesting Device state.
[5/23/2020, 15:51:50] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current App state data: { appId: 'netflix', returnValue: true, windowId: '', processId: '' }
[5/23/2020, 15:51:50] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Input successful: Netflix netflix
[5/23/2020, 15:51:50] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Power state data: {
  returnValue: true,
  state: 'Active',
  processing: 'Screen Saver Ready'
}
[5/23/2020, 15:51:50] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Power state successful: ON
[5/23/2020, 15:51:50] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Audio state data: {
  returnValue: true,
  scenario: 'mastervolume_ext_speaker_arc',
  volume: 0,
  muted: false
}
[5/23/2020, 15:51:50] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Mute state: OFF
[5/23/2020, 15:51:50] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Volume level: 0
[5/23/2020, 15:51:50] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Channel data: { returnValue: false, errorCode: -1000, errorText: 'internal error' }
[5/23/2020, 15:51:50] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Channel successful: undefined, undefined, undefined
[5/23/2020, 15:51:52] [LgWebOsTv] Device: 172.16.1.61 LG TV, requesting Device state.
[5/23/2020, 15:51:52] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current App state data: { appId: 'netflix', returnValue: true, windowId: '', processId: '' }
[5/23/2020, 15:51:52] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Input successful: Netflix netflix
[5/23/2020, 15:51:52] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Power state data: { returnValue: true, state: 'Screen Saver' }
[5/23/2020, 15:51:52] [LgWebOsTv] Device: 172.16.1.61 LG TV, get current Power state successful: OFF
[5/23/2020, 15:51:52] [LgWebOsTv] Device: 172.16.1.61 LG TV, disconnected.

**Comment by HollowCanine** [comment]
If I restart homebridge after the error while the screen saver is still running I get this:
```
[5/23/2020, 16:03:31] [LgWebOsTv] -------- LG TV --------
[5/23/2020, 16:03:31] [LgWebOsTv] Manufacturer: LG Electronics
[5/23/2020, 16:03:31] [LgWebOsTv] Model: homebridge-lgwebos-tv
[5/23/2020, 16:03:31] [LgWebOsTv] System: undefined
[5/23/2020, 16:03:31] [LgWebOsTv] Serialnumber: SN0000004
[5/23/2020, 16:03:31] [LgWebOsTv] Firmware: FW0000004
[5/23/2020, 16:03:31] [LgWebOsTv] ----------------------------------
[5/23/2020, 16:03:32] [LgWebOsTv] Device: 172.16.1.61 LG TV, state: Online.
[5/23/2020, 16:03:32] [LgWebOsTv] Device: 172.16.1.61 LG TV, connected.
[5/23/2020, 16:03:32] [LgWebOsTv] Device: 172.16.1.61 LG TV, get System info error: Error: not connected
    at LGTV.send (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:196:20)
    at LGTV.request (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:181:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:220:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[5/23/2020, 16:03:32] [LgWebOsTv] Device: 172.16.1.61 LG TV, get Software info error: Error: not connected
    at LGTV.send (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:196:20)
    at LGTV.request (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:181:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:239:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```

**Comment by grzegorz914** [comment]
Ok, I will fix this tomorrow
