### ISSUE TITLE
RC Commands restart homebridge 'tme not defined'

### ISSUE THREAD

**Issue by Scoobdriver** [grzegorz914/homebridge-lgwebos-tv#31]
homebridge-lgwebos-tv v0.10.66

eferenceError: tme is not defined
    at lgwebosTvDevice.setRemoteKey (/homebridge/node_modules/homebridge-lgwebos-tv/index.js:755:31)
    at RemoteKey.emit (events.js:310:20)
    at RemoteKey.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at RemoteKey.Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:625:12)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1437:24
    at Array.forEach (<anonymous>)
    at Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:1279:10)
    at HAPServer.emit (events.js:310:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/EventEmitter.ts:42:22)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/HAPServer.ts:8

**Comment by Scoobdriver** [comment]
Updated to 0.10.68 Now fails to start 

TypeError: Cannot read property 'updateCharacteristic' of undefined
    at Object.3ba539f40004 (/homebridge/node_modules/homebridge-lgwebos-tv/index.js:379:27)
    at WebSocketConnection.<anonymous> (/homebridge/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:146:48)
    at WebSocketConnection.emit (events.js:310:20)
    at WebSocketConnection.processFrame (/homebridge/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /homebridge/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:323:40
