### ISSUE TITLE
Plugin is crashing on restart after updating to 0.10.79

### ISSUE THREAD

**Issue by Superwuzy** [grzegorz914/homebridge-lgwebos-tv#32]
After updating to homebridge-lgwebos-tv v0.10.79, the plugin crashes:

`TypeError: Cannot read property 'indexOf' of undefined
    at Object.7d196e630004 (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:371:46)
    at WebSocketConnection.<anonymous> (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:146:48)
    at WebSocketConnection.emit (events.js:310:20)
    at WebSocketConnection.processFrame (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:79:11)`

With the previous version everything was running smoothly.

**Comment by Superwuzy** [comment]
Ooops, the adapter is being updated in very short intervals. Version .82 runs smoothly again.
