### ISSUE TITLE
Plugin causes homebridge to crash

### ISSUE THREAD

**Issue by nstefanelli** [grzegorz914/homebridge-lgwebos-tv#34]
(Latest version) Plugin when loaded causes homebridge to crash. Only able to use after removing plugin.

**Comment by grzegorz914** [comment]
log?

**Comment by dbrookes** [comment]
If volume control is set to true, it crashes on startup with the following

```
[5/23/2020, 17:00:52] [LgWebOsTv] Device: 192.168.1.239 LG TV, state: Online.
[5/23/2020, 17:00:52] TypeError: Cannot read property 'updateValue' of undefined
    at Lightbulb.Service._this.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:324:34)
    at /usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:404:24
    at Object.callbacks.<computed> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:216:25)
    at WebSocketConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:146:48)
    at WebSocketConnection.emit (events.js:310:20)
    at WebSocketConnection.processFrame (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```

**Comment by grzegorz914** [comment]
Please update Your plugin, U use old version.

**Comment by dbrookes** [comment]
Still happens on the latest version (0.10.96) - but only when volume is enabled:

```
[5/23/2020, 17:32:36] TypeError: Cannot read property 'updateValue' of undefined
    at Lightbulb.Service._this.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:324:34)
    at /usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:404:24
    at Object.callbacks.<computed> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:216:25)
    at WebSocketConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:146:48)
    at WebSocketConnection.emit (events.js:310:20)
    at WebSocketConnection.processFrame (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

[5/23/2020, 17:32:36] Got SIGTERM, shutting down Homebridge...
```

```
[5/23/2020, 17:32:36] [LgWebOsTv] Device: 192.168.1.239 LG TV, RC socket connected.
[5/23/2020, 17:32:37] [LgWebOsTv] -------- LG TV --------
[5/23/2020, 17:32:37] [LgWebOsTv] Manufacturer: LG Electronics
[5/23/2020, 17:32:37] [LgWebOsTv] Model: 43UK6300PLB
[5/23/2020, 17:32:37] [LgWebOsTv] System: webOSTV 4.0
```

**Comment by nstefanelli** [comment]
My logs look like the same above.

**Comment by grzegorz914** [comment]
check please latest version
