### ISSUE TITLE
Plugin causes home bridge to crash (0.10.96) - but only when volume is enabled:

### ISSUE THREAD

**Issue by nstefanelli** [grzegorz914/homebridge-lgwebos-tv#35]
Still happens on the latest version (0.10.96) - but only when volume is enabled:

```
[5/23/2020, 17:32:36] TypeError: Cannot read property 'updateValue' of undefined
    at Lightbulb.Service._this.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:324:34)
    at /usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:404:24
    at Object.callbacks.<computed> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:216:25)
    at WebSocketConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:146:48)
    at WebSocketConnection.emit (events.js:310:20)
    at WebSocketConnection.processFrame (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

[5/23/2020, 17:32:36] Got SIGTERM, shutting down Homebridge...
```

```
[5/23/2020, 17:32:36] [LgWebOsTv] Device: 192.168.1.239 LG TV, RC socket connected.
[5/23/2020, 17:32:37] [LgWebOsTv] -------- LG TV --------
[5/23/2020, 17:32:37] [LgWebOsTv] Manufacturer: LG Electronics
[5/23/2020, 17:32:37] [LgWebOsTv] Model: 43UK6300PLB
[5/23/2020, 17:32:37] [LgWebOsTv] System: webOSTV 4.0
```

_Originally posted by @dbrookes in https://github.com/grzegorz914/homebridge-lgwebos-tv/issues/34#issuecomment-633090443_

**Comment by angyp** [comment]
Still happening in 0.11.9

**Comment by angyp** [comment]
Actually works if not configured or as a FAN just not as a slider (light bulb).
TypeError: Cannot read property 'updateValue' of undefined
    at Lightbulb.Service._this.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:324:34)
    at /usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:412:24
    at Object.callbacks.<computed> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:216:25)
    at WebSocketConnection.<anonymous> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:146:48)
    at WebSocketConnection.emit (events.js:316:20)
    at WebSocketConnection.processFrame (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:554:26)
    at /usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:323:40
    at processTicksAndRejections (internal/process/task_queues.js:79:11)

**Comment by angyp** [comment]
Why is it asking for the TV sate Every 2 seconds also
[5/24/2020, 1:30:13 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, requesting Device state.
[5/24/2020, 1:30:13 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current App state data: { appId: 'netflix', returnValue: true, windowId: '', processId: '' }
[5/24/2020, 1:30:13 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Input successful: Netflix netflix
[5/24/2020, 1:30:13 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Power state data: { returnValue: true, state: 'Active' }
[5/24/2020, 1:30:13 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Power state successful: ON
[5/24/2020, 1:30:13 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Audio state data: {
  returnValue: true,
  scenario: 'mastervolume_ext_speaker_arc',
  volume: 6,
  muted: false,
  volumeMax: 100
}
[5/24/2020, 1:30:13 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Mute state: OFF
[5/24/2020, 1:30:13 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Volume level: 6
[5/24/2020, 1:30:13 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Channel data: { returnValue: false, errorCode: -1000, errorText: 'internal error' }
[5/24/2020, 1:30:13 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Channel successful: undefined, undefined, undefined
[5/24/2020, 1:30:15 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, requesting Device state.
[5/24/2020, 1:30:15 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current App state data: { appId: 'netflix', returnValue: true, windowId: '', processId: '' }
[5/24/2020, 1:30:15 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Input successful: Netflix netflix
[5/24/2020, 1:30:15 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Power state data: { returnValue: true, state: 'Active' }
[5/24/2020, 1:30:15 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Power state successful: ON
[5/24/2020, 1:30:15 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Audio state data: {
  returnValue: true,
  scenario: 'mastervolume_ext_speaker_arc',
  volume: 6,
  muted: false,
  volumeMax: 100
}
[5/24/2020, 1:30:15 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Mute state: OFF
[5/24/2020, 1:30:15 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Volume level: 6
[5/24/2020, 1:30:15 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Channel data: { returnValue: false, errorCode: -1000, errorText: 'internal error' }
[5/24/2020, 1:30:15 PM] [LgWebOsTv] Device: 192.168.15.143 Lounge Television, get current Channel successful: undefined, undefined, undefined
