### ISSUE TITLE
get System info error: Error: not connected

### ISSUE THREAD

**Issue by misanthrophy** [grzegorz914/homebridge-lgwebos-tv#38]
Since the latest two updates I receive this error and therefore my homebridge does no longer start:

"[5/25/2020, 22:10:02] [LgWebOsTv] Device: 192.168.178.11 Fernseher, get System info error: Error: not connected
    at LGTV.send (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:196:20)
    at LGTV.request (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:181:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:235:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)"

**Comment by misanthrophy** [comment]
Rolled back to homebridge-lgwebos-tv@0.11.33 which works just fine

**Comment by Lui5Jacint0** [comment]
Same error

**Comment by kmputnam** [comment]
Same error here - rolling back to 0.11.33 fixed it for me.

**Comment by grzegorz914** [comment]
check with latest ob this still exist

**Comment by misanthrophy** [comment]
Still the sams error message, but now homebridge is no longer in bootloop.

Device stays offline and any input made over Home, shows auccessfull execution in my log, but nothing happens. No input change, no power off..

**Comment by misanthrophy** [comment]
[5/26/2020, 19:36:08] [LgWebOsTv] Device: 192.168.178.11 Fernseher, state: Online.
[5/26/2020, 19:36:09] [LgWebOsTv] Device: 192.168.178.11 Fernseher, connected.
[5/26/2020, 19:36:09] [LgWebOsTv] Device: 192.168.178.11 Fernseher, get current Power state successful: ON
[5/26/2020, 19:36:09] [LgWebOsTv] Device: 192.168.178.11 Fernseher, disconnected.
[5/26/2020, 19:36:09] [LgWebOsTv] Device: 192.168.178.11 Fernseher, get System info error: Error: not connected
    at LGTV.send (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:196:20)
    at LGTV.request (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:181:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:231:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[5/26/2020, 19:36:09] [LgWebOsTv] Device: 192.168.178.11 Fernseher, get Software info error: Error: not connected
    at LGTV.send (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:196:20)
    at LGTV.request (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:181:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:250:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[5/26/2020, 19:36:09] [LgWebOsTv] -------- Fernseher --------
[5/26/2020, 19:36:09] [LgWebOsTv] Manufacturer: LG Electronics
[5/26/2020, 19:36:09] [LgWebOsTv] Model: homebridge-lgwebos-tv
[5/26/2020, 19:36:09] [LgWebOsTv] System: undefined
[5/26/2020, 19:36:09] [LgWebOsTv] Serialnumber: SN0000004
[5/26/2020, 19:36:09] [LgWebOsTv] Firmware: FW0000004
[5/26/2020, 19:36:09] [LgWebOsTv] ----------------------------------

homebridge-lgwebos-tv v0.11.103

**Comment by grzegorz914** [comment]
I move this error to debug level because For TV do not get this info, updated

**Comment by misanthrophy** [comment]
So it is now save to update for TV's with webOS V<2?

**Comment by Lui5Jacint0** [comment]
30/05/2020, 21:26:21 [LgWebOsTv] Device: 192.168.1.172 Luis LG TV, connected.
30/05/2020, 21:26:21 [LgWebOsTv] Device: 192.168.1.172 Luis LG TV, get current Power state successful: ON
30/05/2020, 21:26:21 [LgWebOsTv] Device: 192.168.1.172 Luis LG TV, disconnected.
30/05/2020, 21:26:21 TypeError: Cannot read property 'updateCharacteristic' of undefined
    at LGTV.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:189:27)
    at LGTV.emit (events.js:223:5)
    at WebSocketConnection.<anonymous> (/home/hoobs/.hoobs/node_modules/lgtv2/index.js:108:18)
    at WebSocketConnection.emit (events.js:223:5)
    at WebSocketConnection.handleSocketClose (/home/hoobs/.hoobs/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at Socket.emit (events.js:223:5)
    at TCP.<anonymous> (net.js:664:12

**Comment by grzegorz914** [comment]
Still the error present?
