### ISSUE TITLE
Old LG Tv not working

### ISSUE THREAD

**Issue by sapi100** [grzegorz914/homebridge-lgwebos-tv#43]
With the new update my LG 55 "does not work anymore, HB does not start. I have tried with my other LG 43" newer TV and it works ok.
My LG 55 "worked with the old version. I'll get it in Log

,27.5.2020 01.29.48 [LgWebOsTv] Device: 192.168.0.180 TV LG 55, disconnected.
27.5.2020 01.29.48 TypeError: Cannot read property 'updateCharacteristic' of undefined
    at LGTV.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:194:27)
    at LGTV.emit (events.js:223:5)
    at WebSocketConnection.<anonymous> (/home/hoobs/.hoobs/node_modules/lgtv2/index.js:108:18)
    at WebSocketConnection.emit (events.js:223:5)
    at WebSocketConnection.handleSocketClose (/home/hoobs/.hoobs/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at Socket.emit (events.js:223:5)
    at TCP.<anonymous> (net.js:664:12)
27.5.2020 01.29.48 Got SIGTERM, shutting down Bridge...

**Comment by grzegorz914** [comment]
try latest version

**Comment by sapi100** [comment]
With the new version 0.11.106 my LG 43 seems ok.
LG 55 is not responding, 
Now my Hoobs is restarting after update without errors.

**Comment by grzegorz914** [comment]
remove the 55 from HomeKit change its name inn HB restart HB and add it again to the HomeKit

**Comment by sapi100** [comment]
new version again, unfortunately there must be some ip conflict, Hoobs does not boot again, I have to remove LG 55 configuration. I only have the other LG 43 in.

**Comment by grzegorz914** [comment]
please post your config here

**Comment by sapi100** [comment]
{
        "name": "TV LG 55",
        "host": "192.168.0.144",
        "mac": "c8:02:10:41:68:80",
        "volumeControl": 1,
        "switchInfoMenu": false,
        "inputs": [
            {
                "name": "Live TV",
                "reference": "com.webos.app.livetv",
                "type": "TUNER",
                "mode": 0
            },
            {
                "name": "Blu-Ray",
                "reference": "com.webos.app.hdmi1",
                "type": "HDMI1",
                "mode": 0
            },
            {
                "name": "Sat",
                "reference": "com.webos.app.hdmi2",
                "type": "HDMI2",
                "mode": 0
            },
            {
                "name": "Apple Tv",
                "reference": "com.webos.app.hdmi3",
                "type": "HDMI3",
                "mode": 0
            },
            {
                "name": "HDMI 4",
                "reference": "com.webos.app.hdmi4",
                "type": "HDMI4",
                "mode": 0
            },
            {
                "name": "Netflix",
                "reference": "netflix",
                "type": "APPLICATION",
                "mode": 0
            },
            {
                "name": "YouTube",
                "reference": "youtube.leanback.v4",
                "type": "APPLICATION",
                "mode": 0
            },
            {
                "name": "LG Store",
                "reference": "com.webos.app.discovery",
                "type": "APPLICATION",
                "mode": 0
            }
        ]
    }

**Comment by grzegorz914** [comment]
complete config with all TV's and platform config

**Comment by sapi100** [comment]
{
    "server": {
        "port": 8080,
        "origin": "*",
        "autostart": 0,
        "home_setup_id": "X-HM://0023ISYWY0O0G",
        "polling_seconds": 5
    },
    "client": {
        "default_route": "status",
        "inactive_logoff": 30,
        "theme": "hoobs-light",
        "locale": "en",
        "temp_units": "celsius",
        "country_code": "DK",
        "postal_code": "2660"
    },
    "bridge": {
        "name": "HOOBS",
        "port": 51826,
        "pin": "031-45-154",
        "username": "FD:0A:DB:13:8A:61"
    },
    "description": "",
    "ports": {},
    "accessories": [
        
        {
            "platform": "OpenWebIfTv",
            "plugin_map": {
                "plugin_name": "homebridge-openwebif-tv"
            },
            "devices": [
                {
                    "name": "Sat Vu+Duo_2",
                    "host": "192.168.0.190",
                    "port": 80,
                    "auth": false,
                    "user": "1234",
                    "pass": "1234",
                    "volumeControl": 0,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "DR1 HD",
                            "reference": "1:0:19:12CB:30:46:E080000:0:0:0:"
                        },
                        {
                            "name": "TV2 DK",
                            "reference": "1:0:19:1BB8:23:46:E080000:0:0:0:"
                        },
                        {
                            "name": "TV3 HD",
                            "reference": "1:0:19:1B91:41:46:E080000:0:0:0:"
                        },
                        {
                            "name": "TV3+ HD",
                            "reference": "1:0:19:1B8A:1C:46:E080000:0:0:0:"
                        },
                        {
                            "name": "ID Discovery",
                            "reference": "1:0:16:1C8F:A:46:E080000:0:0:0:"
                        },
                        {
                            "name": "TV2 Fri HD",
                            "reference": "1:0:19:469:3D:46:E080000:0:0:0:"
                        },
                        {
                            "name": "TV2 News",
                            "reference": "1:0:19:1E2E:23:46:E080000:0:0:0:"
                        },
                        {
                            "name": "TV2 Charlie HD",
                            "reference": "1:0:19:1E2D:23:46:E080000:0:0:0:"
                        },
                        {
                            "name": "DR2",
                            "reference": "1:0:16:1C96:A:46:E080000:0:0:0:"
                        },
                        {
                            "name": "Discovery HD",
                            "reference": "1:0:19:1C3C:21:46:E080000:0:0:0:"
                        },
                        {
                            "name": "Discovery Science",
                            "reference": "1:0:16:1C7F:2B:46:E080000:0:0:0:"
                        },
                        {
                            "name": "History Chnl HD",
                            "reference": "1:0:1:106E:29:46:E080000:0:0:0:"
                        },
                        {
                            "name": "HISTORY 2 HD",
                            "reference": "1:0:19:1C1F:29:46:E080000:0:0:0:"
                        },
                        {
                            "name": "Animal Planet HD",
                            "reference": "1:0:19:1C19:3D:46:E080000:0:0:0:"
                        },
                        {
                            "name": "Nat Geo HD",
                            "reference": "1:0:19:448:18:46:E080000:0:0:0:"
                        },
                        {
                            "name": "Nat Geo Wild HD",
                            "reference": "1:0:19:1C46:29:46:E080000:0:0:0:"
                        },
                        {
                            "name": "Eurosport 1 HD",
                            "reference": "1:0:19:1C45:42:46:E080000:0:0:0:"
                        },
                        {
                            "name": "Eurosport 2 HD",
                            "reference": "1:0:19:1BA0:3F:46:E080000:0:0:0:"
                        },
                        {
                            "name": "BBC BRIT HD",
                            "reference": "1:0:19:1C08:2B:46:E080000:0:0:0:"
                        },
                        {
                            "name": "C More Stars HD",
                            "reference": "1:0:19:1B76:42:46:E080000:0:0:0:"
                        },
                        {
                            "name": "C More First HD",
                            "reference": "1:0:19:CEA:E:46:E080000:0:0:0:"
                        },
                        {
                            "name": "C More Hits HD",
                            "reference": "1:0:19:1AF7:E:46:E080000:0:0:0:"
                        },
                        {
                            "name": "C More Series HD",
                            "reference": "1:0:19:584:E:46:E080000:0:0:0:"
                        },
                        {
                            "name": "M1 HD",
                            "reference": "1:0:1:FC8:D:1:E082E2F:0:0:0:"
                        },
                        {
                            "name": "M4 Sport HD",
                            "reference": "1:0:19:791E:2C6:600:E080000:0:0:0:"
                        },
                        {
                            "name": "Duna HD",
                            "reference": "1:0:19:7919:2C6:600:E080000:0:0:0:"
                        },
                        {
                            "name": "Duna World",
                            "reference": "1:0:1:7608:2BE:600:E080000:0:0:0:"
                        },
                        {
                            "name": "TV2 Hu",
                            "reference": "1:0:1:7602:2BE:600:E080000:0:0:0:"
                        },
                        {
                            "name": "RTL Klub",
                            "reference": "1:0:1:7601:2BE:600:E080000:0:0:0:"
                        }
                    ]
                },
                {
                    "name": "Sat Vu+Solo_2",
                    "host": "192.168.0.175",
                    "port": 80,
                    "auth": false,
                    "user": "1234",
                    "pass": "1234",
                    "volumeControl": 0,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "DR1 HD",
                            "reference": "1:0:19:12CB:30:46:E080000:0:0:0:"
                        },
                        {
                            "name": "TV2 DK",
                            "reference": "1:0:19:1BB8:23:46:E080000:0:0:0:"
                        },
                        {
                            "name": "TV3 HD",
                            "reference": "1:0:19:1B91:41:46:E080000:0:0:0:"
                        },
                        {
                            "name": "TV3+ HD",
                            "reference": "1:0:19:1B8A:1C:46:E080000:0:0:0:"
                        },
                        {
                            "name": "ID Discovery",
                            "reference": "1:0:16:1C8F:A:46:E080000:0:0:0:"
                        },
                        {
                            "name": "TV2 Fri HD",
                            "reference": "1:0:19:469:3D:46:E080000:0:0:0:"
                        },
                        {
                            "name": "TV2 News",
                            "reference": "1:0:19:1E2E:23:46:E080000:0:0:0:"
                        },
                        {
                            "name": "TV2 Charlie HD",
                            "reference": "1:0:19:1E2D:23:46:E080000:0:0:0:"
                        },
                        {
                            "name": "DR2",
                            "reference": "1:0:16:1C96:A:46:E080000:0:0:0:"
                        },
                        {
                            "name": "Discovery HD",
                            "reference": "1:0:19:1C3C:21:46:E080000:0:0:0:"
                        },
                        {
                            "name": "Discovery Science",
                            "reference": "1:0:16:1C7F:2B:46:E080000:0:0:0:"
                        },
                        {
                            "name": "History Chnl HD",
                            "reference": "1:0:1:106E:29:46:E080000:0:0:0:"
                        },
                        {
                            "name": "HISTORY 2 HD",
                            "reference": "1:0:19:1C1F:29:46:E080000:0:0:0:"
                        },
                        {
                            "name": "Animal Planet HD",
                            "reference": "1:0:19:1C19:3D:46:E080000:0:0:0:"
                        },
                        {
                            "name": "Nat Geo HD",
                            "reference": "1:0:19:448:18:46:E080000:0:0:0:"
                        },
                        {
                            "name": "Nat Geo Wild HD",
                            "reference": "1:0:19:1C46:29:46:E080000:0:0:0:"
                        },
                        {
                            "name": "Eurosport 1 HD",
                            "reference": "1:0:19:1C45:42:46:E080000:0:0:0:"
                        },
                        {
                            "name": "Eurosport 2 HD",
                            "reference": "1:0:19:1BA0:3F:46:E080000:0:0:0:"
                        },
                        {
                            "name": "BBC BRIT HD",
                            "reference": "1:0:19:1C08:2B:46:E080000:0:0:0:"
                        },
                        {
                            "name": "C More Stars HD",
                            "reference": "1:0:19:1B76:42:46:E080000:0:0:0:"
                        },
                        {
                            "name": "C More First HD",
                            "reference": "1:0:19:CEA:E:46:E080000:0:0:0:"
                        },
                        {
                            "name": "C More Hits HD",
                            "reference": "1:0:19:1AF7:E:46:E080000:0:0:0:"
                        },
                        {
                            "name": "C More Series HD",
                            "reference": "1:0:19:584:E:46:E080000:0:0:0:"
                        },
                        {
                            "name": "M1 HD",
                            "reference": "1:0:1:FC8:D:1:E082E2F:0:0:0:"
                        },
                        {
                            "name": "M4 Sport HD",
                            "reference": "1:0:19:791E:2C6:600:E080000:0:0:0:"
                        },
                        {
                            "name": "Duna HD",
                            "reference": "1:0:19:7919:2C6:600:E080000:0:0:0:"
                        },
                        {
                            "name": "Duna World",
                            "reference": "1:0:1:7608:2BE:600:E080000:0:0:0:"
                        },
                        {
                            "name": "TV2 Hu",
                            "reference": "1:0:1:7602:2BE:600:E080000:0:0:0:"
                        },
                        {
                            "name": "RTL Klub",
                            "reference": "1:0:1:7601:2BE:600:E080000:0:0:0:"
                        }
                    ]
                }
            ]
        },
        
        
        {
            "platform": "LgWebOsTv",
            "plugin_map": {
                "plugin_name": "homebridge-lgwebos-tv"
            },
            "devices": [
                {
                    "name": "TV LG 43",
                    "host": "192.168.0.110",
                    "mac": "00:51:ed:f1:19:4a",
                    "volumeControl": 1,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "Live TV",
                            "reference": "com.webos.app.livetv",
                            "type": "TUNER",
                            "mode": 0
                        },
                        {
                            "name": "Blu-Ray",
                            "reference": "com.webos.app.hdmi1",
                            "type": "HDMI1",
                            "mode": 0
                        },
                        {
                            "name": "Sat",
                            "reference": "com.webos.app.hdmi2",
                            "type": "HDMI2",
                            "mode": 0
                        },
                        {
                            "name": "Apple Tv",
                            "reference": "com.webos.app.hdmi3",
                            "type": "HDMI3",
                            "mode": 0
                        },
                        {
                            "name": "HDMI 4",
                            "reference": "com.webos.app.hdmi4",
                            "type": "HDMI4",
                            "mode": 0
                        },
                        {
                            "name": "Netflix",
                            "reference": "netflix",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "YouTube",
                            "reference": "youtube.leanback.v4",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "LG Store",
                            "reference": "com.webos.app.discovery",
                            "type": "APPLICATION",
                            "mode": 0
                        }
                    ]
                },
		{
                    "name": "TV LG 55",
                    "host": "192.168.0.144",
                    "mac": "c8:02:10:41:68:80",
                    "volumeControl": 1,
                    "switchInfoMenu": false,
                    "inputs": [
                        {
                            "name": "Live TV",
                            "reference": "com.webos.app.livetv",
                            "type": "TUNER",
                            "mode": 0
                        },
                        {
                            "name": "Blu-Ray",
                            "reference": "com.webos.app.hdmi1",
                            "type": "HDMI1",
                            "mode": 0
                        },
                        {
                            "name": "Sat",
                            "reference": "com.webos.app.hdmi2",
                            "type": "HDMI2",
                            "mode": 0
                        },
                        {
                            "name": "Apple Tv",
                            "reference": "com.webos.app.hdmi3",
                            "type": "HDMI3",
                            "mode": 0
                        },
                        {
                            "name": "HDMI 4",
                            "reference": "com.webos.app.hdmi4",
                            "type": "HDMI4",
                            "mode": 0
                        },
                        {
                            "name": "Netflix",
                            "reference": "netflix",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "YouTube",
                            "reference": "youtube.leanback.v4",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "LG Store",
                            "reference": "com.webos.app.discovery",
                            "type": "APPLICATION",
                            "mode": 0
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by grzegorz914** [comment]
this config is wrong, change accessories to platforms:
```
"platforms": [
here all platform
]
```

**Comment by sapi100** [comment]
I have removed the LG 55 TV from LgWebOsTv and only run it one TV.
Then Hoobs runs again and the LG 43 Tv also. I have to try with ethernet cable

**Comment by grzegorz914** [comment]
You need to change Your config, as I described in previous post

**Comment by sapi100** [comment]
I have uninstalled and will reinstall from Hoobs but version is only 0.11.115 published 6/6/2020 • 2 days ago
I have tried another old plugin LG webOS3 Tcpp but it is only volume and on / off can be controlled.
Your old version also worked before you redesigned the new Inputs. After that update my LG TV did not respond to it anymore. I would like to use the old version that worked on my TV.

**Comment by grzegorz914** [comment]
Remove it formę HomeKit, change name in config.json, restart HB, ad it again to The KomeKit

**Comment by sapi100** [comment]
It's ok with Hoobs and Homekit too but TVs don't respond.
![2020-06-09](https://user-images.githubusercontent.com/63670326/84116303-d6abf580-aa2f-11ea-9f79-3d1844626f1e.png)

**Comment by grzegorz914** [comment]
Please enable debug Mode and get The log.

**Comment by sapi100** [comment]
![2020-06-09](https://user-images.githubusercontent.com/63670326/84124266-48d60780-aa3b-11ea-9636-9d2041946b11.png)

**Comment by sapi100** [comment]
![2020-06-09 (3)](https://user-images.githubusercontent.com/63670326/84124339-5f7c5e80-aa3b-11ea-8877-43f362d79cb9.png)

**Comment by grzegorz914** [comment]
Here is nothing from debug mode, U need to run homebridge -D

**Comment by sapi100** [comment]
My command is hoobs -d
I get the pictures
![2020-06-09 (4)](https://user-images.githubusercontent.com/63670326/84151790-23a9bf00-aa64-11ea-9295-06bbc9c8f488.png)

**Comment by grzegorz914** [comment]
Here is nothing from Debug of LgWebOs plugin.

**Comment by sapi100** [comment]
I'm getting into debug mode with command hoobs -d
What should I do afterwards?

**Comment by grzegorz914** [comment]
U need to run homebridge in debug mode not the hoobs

**Comment by sapi100** [comment]
I can't do that.

**Comment by grzegorz914** [comment]
Try latest release and get fedback

**Comment by grzegorz914** [comment]
I close this because no activity, if this happens again free to open it.
