### ISSUE TITLE
Error after update to 0.11.110

### ISSUE THREAD

**Issue by Superwuzy** [grzegorz914/homebridge-lgwebos-tv#44]
```
ReferenceError: openwebIfTvDevice is not defined
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:44:32)
    at HomebridgeAPI.emit (events.js:322:22)
    at HomebridgeAPI.signalFinished (/usr/lib/node_modules/homebridge/src/api.ts:251:10)
    at Server.start (/usr/lib/node_modules/homebridge/src/server.ts:159:14)
    at cli (/usr/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
```

**Comment by siobhanellis** [comment]
I'm seeing the same issue.

[5/27/2020, 6:48:18 AM] ReferenceError: openwebIfTvDevice is not defined
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:44:32)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:251:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:14)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
