### ISSUE TITLE
Error while using 0.11.0114

### ISSUE THREAD

**Issue by Superwuzy** [grzegorz914/homebridge-lgwebos-tv#48]
TypeError: Cannot read property 'updateCharacteristic' of undefined
    at LGTV.<anonymous> (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:190:27)
    at LGTV.emit (events.js:315:20)
    at WebSocketConnection.<anonymous> (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:108:18)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.handleSocketClose (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)

**Comment by grzegorz914** [comment]
This was fixed in 115.
