### ISSUE TITLE
This plugin is crashing Homebridge

### ISSUE THREAD

**Issue by agneevX** [grzegorz914/homebridge-lgwebos-tv#51]
Tried reinstalling, same thing.

```
[6/6/2020, 3:08:46 PM] TypeError: Cannot read property 'updateCharacteristic' of undefined
    at LGTV.<anonymous> (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:190:27)
    at LGTV.emit (events.js:315:20)
    at WebSocketConnection.<anonymous> (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:108:18)
    at WebSocketConnection.emit (events.js:315:20)
    at WebSocketConnection.handleSocketClose (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketConnection.js:389:14)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)
```

Homebridge keeps restarting and crashing...

**Comment by grzegorz914** [comment]
I have no any crash on 3 TV, are U running Hoobs?

**Comment by agneevX** [comment]
> I have no any crash on 3 TV, are U running Hoobs?

Nope. Just standard HB install on RPi 4 running Buster.
