### ISSUE TITLE
TV doesn't Respond to homebridge

### ISSUE THREAD

**Issue by Lui5Jacint0** [grzegorz914/homebridge-lgwebos-tv#53]
Config:

`"devices": [
                {
                    "name": "LGWebOS2",
                    "host": "192.168.1.172",
                    "mac": "3C:CD:93:9D:F5:68",
                    "volumeControl": 1,
                    "switchInfoMenu": true,
                    "supportOldWebOs": true,
                    "inputs": [
                        {
                            "name": "Netflix",
                            "reference": "netflix",
                            "type": "APPLICATION",
                            "mode": 0
                        },
                        {
                            "name": "Chromecast",
                            "reference": "com.webos.app.hdmi2",
                            "type": "HDMI",
                            "mode": 0
                        },
                        {
                            "name": "MEO",
                            "reference": "com.webos.app.hdmi1",
                            "type": "HDMI",
                            "mode": 0
                        },
                        {
                            "name": "YouTube",
                            "reference": "youtube.leanback.v4",
                            "type": "APPLICATION",
                            "mode": 0
                        }
                    ]
                }
            ],
            "platform": "LgWebOsTv"
        }
    ]
}`

Debug
`[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, connecting...
[6/11/2020, 14:49:23] [LgWebOsTv] prepareTelevisionService
[6/11/2020, 14:49:23] [LgWebOsTv] prepareSpeakerService
[6/11/2020, 14:49:23] [LgWebOsTv] prepareVolumeService
[6/11/2020, 14:49:23] [LgWebOsTv] prepareInputsService
[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, read customInputsFile failed, error: Error: ENOENT: no such file or directory, open '/home/pi/.homebridge/lgwebosTv/customInputs_1921681172'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at lgwebosTvDevice.prepareInputsService (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:518:31)
    at lgwebosTvDevice.prepareTelevisionService (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:451:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/pi/.homebridge/lgwebosTv/customInputs_1921681172'
}
[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, publishExternalAccessories.
[6/11/2020, 14:49:23] LGWebOS2 is running on port 34009.
[6/11/2020, 14:49:23] Please add [LGWebOS2] manually in Home app. Setup Code: 031-45-154
[6/11/2020, 14:49:23] Got SIGTERM, shutting down Homebridge...
[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, connected.
[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Power state successful: ON
[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, requesting Device state.
[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, requesting Device state.
[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, connecting to RC socket...
[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Power state data: {}
[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Power state successful: OFF
[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, disconnected.
[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, requesting Device information.
[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get System info error: Error: not connected
    at LGTV.send (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:196:20)
    at LGTV.request (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:181:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:228:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get Software info error: Error: not connected
    at LGTV.send (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:196:20)
    at LGTV.request (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:181:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:247:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 Error: not connected
    at LGTV.send (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:196:20)
    at LGTV.request (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:181:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:267:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7), get Services list error: %s
[6/11/2020, 14:49:23] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get Apps list error: Error: not connected
    at LGTV.send (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:196:20)
    at LGTV.request (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:181:14)
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:284:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[6/11/2020, 14:49:23] [WeatherPlus] **Fakegato-timer: addData  Now { time: 1591886963.8, temp: 18, pressure: 1026, humidity: 93 }  immediate:  false
[6/11/2020, 14:49:23] [WeatherPlus] **Start Global Fakegato-Timer - 10min**
[6/11/2020, 14:49:24] [LgWebOsTv] -------- LGWebOS2 --------
[6/11/2020, 14:49:24] [LgWebOsTv] Manufacturer: LG Electronics
[6/11/2020, 14:49:24] [LgWebOsTv] Model: homebridge-lgwebos-tv
[6/11/2020, 14:49:24] [LgWebOsTv] System: undefined
[6/11/2020, 14:49:24] [LgWebOsTv] Serialnr: SN0000004
[6/11/2020, 14:49:24] [LgWebOsTv] Firmware: FW0000004
[6/11/2020, 14:49:24] [LgWebOsTv] ----------------------------------`

I thought HOOBS was the problem so i migrated to homebridge

**Comment by Lui5Jacint0** [comment]
Log:

[6/11/2020, 14:47:06] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Power state successfull, state: OFF
[6/11/2020, 14:47:06] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Input successful: undefined 
[6/11/2020, 14:47:06] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current channel successful:  
[6/11/2020, 14:47:06] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Mute state successful: ON
[6/11/2020, 14:47:06] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:06] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:09] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Power state successfull, state: OFF
[6/11/2020, 14:47:09] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Input successful: undefined 
[6/11/2020, 14:47:09] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current channel successful:  
[6/11/2020, 14:47:09] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Mute state successful: ON
[6/11/2020, 14:47:09] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:09] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:12] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Power state successfull, state: OFF
[6/11/2020, 14:47:12] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Input successful: undefined 
[6/11/2020, 14:47:12] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current channel successful:  
[6/11/2020, 14:47:12] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Mute state successful: ON
[6/11/2020, 14:47:12] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:12] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:18] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, set new Volume level successful: 0
[6/11/2020, 14:47:18] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:18] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Power state successfull, state: OFF
[6/11/2020, 14:47:18] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Input successful: undefined 
[6/11/2020, 14:47:18] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current channel successful:  
[6/11/2020, 14:47:18] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Mute state successful: ON
[6/11/2020, 14:47:18] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:18] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Power state successfull, state: OFF
[6/11/2020, 14:47:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Input successful: undefined 
[6/11/2020, 14:47:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current channel successful:  
[6/11/2020, 14:47:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Mute state successful: ON
[6/11/2020, 14:47:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, set new Volume level successful: 74
[6/11/2020, 14:47:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Power state successfull, state: OFF
[6/11/2020, 14:47:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Input successful: undefined 
[6/11/2020, 14:47:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current channel successful:  
[6/11/2020, 14:47:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Mute state successful: ON
[6/11/2020, 14:47:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:21] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, set new Volume level successful: 23
[6/11/2020, 14:47:21] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:21] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Power state successfull, state: OFF
[6/11/2020, 14:47:21] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Input successful: undefined 
[6/11/2020, 14:47:21] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current channel successful:  
[6/11/2020, 14:47:21] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Mute state successful: ON
[6/11/2020, 14:47:21] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:21] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:22] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Power state successfull, state: OFF
[6/11/2020, 14:47:22] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Input successful: undefined 
[6/11/2020, 14:47:22] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current channel successful:  
[6/11/2020, 14:47:22] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Mute state successful: ON
[6/11/2020, 14:47:22] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:22] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:27] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, set new Power state successful: ON
[6/11/2020, 14:47:27] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Power state successfull, state: OFF
[6/11/2020, 14:47:28] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Power state successfull, state: OFF
[6/11/2020, 14:47:28] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Input successful: undefined 
[6/11/2020, 14:47:28] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current channel successful:  
[6/11/2020, 14:47:28] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Mute state successful: ON
[6/11/2020, 14:47:28] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:28] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:28] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, set new Power state successful: ON
[6/11/2020, 14:47:28] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Power state successfull, state: OFF
[6/11/2020, 14:47:30] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Power state successfull, state: OFF
[6/11/2020, 14:47:30] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Input successful: undefined 
[6/11/2020, 14:47:30] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current channel successful:  
[6/11/2020, 14:47:30] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Mute state successful: ON
[6/11/2020, 14:47:30] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0
[6/11/2020, 14:47:30] [LgWebOsTv] Device: 192.168.1.172 LGWebOS2, get current Volume level successful: 0

**Comment by grzegorz914** [comment]
As U see Your TV does not correct respond to the plugin, Check Your installation, network state etc. Sorry but I have 3 different LG webOS tV and on all working correct.

**Comment by Lui5Jacint0** [comment]
i did a clean install, reset everything, i'm able to control TV but now the remote shuts down the tv with every key.

**Comment by grzegorz914** [comment]
Tested RC right now and all working without any problems.

**Comment by Lui5Jacint0** [comment]
[6/11/2020, 21:59:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOSTV2, setRemoteKey successful, command: ENTER
[6/11/2020, 21:59:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOSTV2, set new Power state successful: OFF
[6/11/2020, 21:59:19] [LgWebOsTv] Device: 192.168.1.172 LGWebOSTV2, disconnected.

**Comment by Lui5Jacint0** [comment]
The version less buggy that i can run is 0.9.101. And the remote still turns off the tv.

**Comment by Karo-X** [comment]
Same issue here on a LG 43UF6809-ZA. No Respond on HomeBridge and Home-App.

**Comment by grzegorz914** [comment]
Try latest beta please.

**Comment by grzegorz914** [comment]
Already fixed
