### ISSUE TITLE
Unable to add TV

### ISSUE THREAD

**Issue by agneevX** [grzegorz914/homebridge-lgwebos-tv#57]
Cannot add my TV

Debug logs
```
[6/22/2020, 1:15:25 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, connecting...
[6/22/2020, 1:15:25 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, waiting on confirmation...
[6/22/2020, 1:15:26 PM] [LgWebOsTv] prepareTelevisionService
[6/22/2020, 1:15:26 PM] [LgWebOsTv] prepareSpeakerService
[6/22/2020, 1:15:26 PM] [LgWebOsTv] prepareInputsService
[6/22/2020, 1:15:26 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, read customInputsFile failed, error: Error: ENOENT: no such file or directory, open '/var/lib/homebridge/lgwebosTv/customInputs_100062'
    at Object.openSync (fs.js:458:3)
    at Object.readFileSync (fs.js:360:35)
    at lgwebosTvDevice.prepareInputsService (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:515:31)
    at lgwebosTvDevice.prepareTelevisionService (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:448:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/var/lib/homebridge/lgwebosTv/customInputs_100062'
}
[6/22/2020, 1:15:26 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, publishExternalAccessories.
[6/22/2020, 1:15:26 PM] Old Room TV is running on port 40793.
[6/22/2020, 1:15:26 PM] Please add [Old Room TV] manually in Home app. Setup Code: 666-66-666
[6/22/2020, 1:15:29 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, state: Online.
[6/22/2020, 1:15:29 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, waiting on confirmation...
[6/22/2020, 1:15:32 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, state: Online.
[6/22/2020, 1:15:32 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, waiting on confirmation...
[6/22/2020, 1:15:36 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, state: Online.
[6/22/2020, 1:15:36 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, waiting on confirmation...
[6/22/2020, 1:15:39 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, state: Online.
[6/22/2020, 1:15:39 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, waiting on confirmation...
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, connected.
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, get current Power state successful: ON
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, requesting Device state.
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, requesting Device state.
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, connecting to RC socket...
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, get current Power state data: {}
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, get current Power state successful: OFF
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, disconnected.
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, requesting Device information.
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, get System info error: Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:196:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:181:14)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:228:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, get Software info error: Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:196:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:181:14)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:247:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:196:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:181:14)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:267:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7), get Services list error: %s
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, get Apps list error: Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:196:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:181:14)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:284:12)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[6/22/2020, 1:15:41 PM] [LgWebOsTv] -------- Old Room TV --------
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Manufacturer: LG Electronics
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Model: homebridge-lgwebos-tv
[6/22/2020, 1:15:41 PM] [LgWebOsTv] System: undefined
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Serialnr: SN0000004
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Firmware: FW0000004
[6/22/2020, 1:15:41 PM] [LgWebOsTv] ----------------------------------
[6/22/2020, 1:16:13 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, get current Power state successfull, state: OFF
```

**Comment by grzegorz914** [comment]
as U see here:
```
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, disconnected.
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, requesting Device information.
[6/22/2020, 1:15:41 PM] [LgWebOsTv] Device: 10.0.0.62 Old Room TV, get System info error: Error: not connected
```

Your TV is not connected.

**Comment by agneevX** [comment]
It was, as a matter of fact.
