### ISSUE TITLE
Start TV with Netflix

### ISSUE THREAD

**Issue by Sebbo02** [grzegorz914/homebridge-lgwebos-tv#61]
Hi,

The plugin is working great - Thanks a lot!

But as I am using my TV mainly with Netflix, I noticed that it is not possible to start the TV with Netflix Open. I always have to switch inputs first in order to then switch to Netflix again.
With my infrared-remote this works by starting the TV with the ,,Netflix“ Button

Do you see any chance to fix that?

**Comment by grzegorz914** [comment]
Try to configure Netflix button and start with it.

**Comment by steinmb** [comment]
I think this is unrelated to Netflix or any of the TV application and more a generic one and I think the issue should be renamed accordingly. Testing this is what I notice. 

If this plugin input config have, lets say Apple TV as the first input defined:

```
            "inputs": [
                {
                    "name": "Apple TV",
                    "reference": "com.apple.appletv",
                    "type": "APPLICATION",
                    "mode": 0
                },
                {
                    "name": "PS4",
                    "reference": "com.webos.app.hdmi4",
                    "type": "HDMI",
                    "mode": 0
                }
            ]
        }
```

And the TV power on default set to example HDMI 4 (PS4 in this example). It will highlight the first application/input as the running one, even if that is incorrect, and there will be no way of selecting on without, as mention above, switching to another input and then back again. You could prob. mitigate that by matching the first input in your plugin config with the one the TV have but would be a hack. Powering on the device by using the Netflix or any of the other custom buttons on the TV remote will also cause the same problem.

**Comment by grzegorz914** [comment]
If U don't have Netflix on the inputs list and start the TV with Netflix Button the list will always remain to the first position.

**Comment by grzegorz914** [comment]
OK,

i see the problem now, will be fixed.

**Comment by steinmb** [comment]
YAY :)

**Comment by grzegorz914** [comment]
Try latest beta and get the feedback

**Comment by grzegorz914** [comment]
try beta 42, I thing I have figured it out

**Comment by steinmb** [comment]
homebridge-lgwebos-tv v1.7.44-beta.42 

```
[3/19/2021, 11:43:12 PM] [LgWebOsTv] Device: 10.0.0.196 TV, set new Power state successful: ON
[3/19/2021, 11:43:15 PM] [LgWebOsTv] Device: 10.0.0.196 TV, set new Input successful: PS4 com.webos.app.hdmi4
[3/19/2021, 11:43:17 PM] [LgWebOsTv] Device: 10.0.0.196 TV, set new Input successful: Apple TV com.apple.appletv
[3/19/2021, 11:43:22 PM] [LgWebOsTv] Device: 10.0.0.196 TV, connecting to TV
[3/19/2021, 11:43:22 PM] [LgWebOsTv] Device: 10.0.0.196 TV, connecting...
[3/19/2021, 11:43:22 PM] [LgWebOsTv] Device: 10.0.0.196 TV, connecting to TV
[3/19/2021, 11:43:22 PM] [LgWebOsTv] Device: 10.0.0.196 TV, connecting...
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, error: Error: Sec-WebSocket-Accept header from server didn't match expected value of mRCFwry3OdJhYNVqRBJ2KRGez/s=
    at WebSocketClient.failHandshake (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:339:32)
    at WebSocketClient.validateHandshake (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:326:14)
    at ClientRequest.handleRequestUpgrade (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:261:14)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketOnData (_http_client.js:508:11)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, error: Error: Sec-WebSocket-Accept header from server didn't match expected value of 7whqWpa877tmVXFz8KMBZC85nuk=
    at WebSocketClient.failHandshake (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:339:32)
    at WebSocketClient.validateHandshake (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:326:14)
    at ClientRequest.handleRequestUpgrade (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:261:14)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketOnData (_http_client.js:508:11)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, connecting to TV
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, connecting...
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, connected.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, RC socket connected.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, requesting Device Info.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get System info error: Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at LGTV.getSocket (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:255:14)
    at LGTV.<anonymous> (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:172:15)
    at LGTV.emit (events.js:314:20)
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get Software info error: Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:229:15
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, requesting Device Info failed, error: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:238:25
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:229:15
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, connected.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, RC socket connected.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, requesting Device Info.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get System info error: Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at LGTV.getSocket (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:255:14)
    at LGTV.<anonymous> (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:172:15)
    at LGTV.emit (events.js:314:20)
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get Software info error: Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:229:15
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, requesting Device Info failed, error: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:238:25
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:229:15
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, connected.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, RC socket connected.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, requesting Device Info.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get System info error: Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at LGTV.getSocket (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:255:14)
    at LGTV.<anonymous> (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:172:15)
    at LGTV.emit (events.js:314:20)
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get Software info error: Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:229:15
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, requesting Device Info failed, error: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:238:25
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:229:15
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, connected.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, RC socket connected.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, requesting Device Info.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get System info error: Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at LGTV.getSocket (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:255:14)
    at LGTV.<anonymous> (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:172:15)
    at LGTV.emit (events.js:314:20)
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get Software info error: Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:229:15
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, requesting Device Info failed, error: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:238:25
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:229:15
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, connected.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, RC socket connected.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, requesting Device Info.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get System info error: Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at LGTV.getSocket (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:255:14)
    at LGTV.<anonymous> (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:172:15)
    at LGTV.emit (events.js:314:20)
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get Software info error: Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:229:15
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, requesting Device Info failed, error: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:238:25
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:229:15
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, connected.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, RC socket connected.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, requesting Device Info.
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get System info error: Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at LGTV.getSocket (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:255:14)
    at LGTV.<anonymous> (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:172:15)
    at LGTV.emit (events.js:314:20)
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get Software info error: Error: not connected
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:20)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:229:15
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, requesting Device Info failed, error: TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:238:25
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:229:15
    at LGTV.send (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:202:17)
    at LGTV.request (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:187:14)
    at lgwebosTvDevice.getDeviceInfo (/usr/lib/node_modules/homebridge-lgwebos-tv/index.js:222:14)
    at /usr/lib/node_modules/homebridge-lgwebos-tv/index.js:177:11
    at /usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:257:17
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, error: Error: Sec-WebSocket-Accept header from server didn't match expected value of jHHK5L8qc9HJdj2j5TVSDvIBCF4=
    at WebSocketClient.failHandshake (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:339:32)
    at WebSocketClient.validateHandshake (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:326:14)
    at ClientRequest.handleRequestUpgrade (/usr/lib/node_modules/homebridge-lgwebos-tv/node_modules/websocket/lib/WebSocketClient.js:261:14)
    at ClientRequest.emit (events.js:314:20)
    at Socket.socketOnData (_http_client.js:508:11)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
[3/19/2021, 11:43:27 PM] [LgWebOsTv] Device: 10.0.0.196 TV, connected.
[3/19/2021, 11:43:28 PM] [LgWebOsTv] Device: 10.0.0.196 TV, RC socket connected.
[3/19/2021, 11:43:28 PM] [LgWebOsTv] Device: 10.0.0.196 TV, requesting Device Info.
[3/19/2021, 11:43:28 PM] [LgWebOsTv] Device: 10.0.0.196 TV, requesting Device state.
[3/19/2021, 11:43:28 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get current App state response: {
  appId: 'com.webos.app.hdmi4',
  subscribed: true,
  returnValue: true,
  windowId: '',
  processId: ''
}
[3/19/2021, 11:43:28 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get current Power state data: { subscribed: true, returnValue: true, state: 'Active' }
[3/19/2021, 11:43:29 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get current Audio state response: {
  volumeStatus: [Object],
  returnValue: true,
  callerId: 'com.webos.service.apiadapter',
  mute: false,
  volume: 23
}
[3/19/2021, 11:43:29 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get System info response: {
  returnValue: true,
  features: [Object],
  receiverType: 'DVB',
  modelName: 'OLED48CX6LB',
  programMode: true
}
[3/19/2021, 11:43:29 PM] [LgWebOsTv] Device: 10.0.0.196 TV, get System info response1: {
  returnValue: true,
  product_name: 'webOSTV 5.0',
  model_name: 'HE_DTV_W20O_AFABABAA',
  sw_type: 'FIRMWARE',
  major_ver: '03',
  minor_ver: '21.16',
  country: 'NO',
  country_group: 'EU',
  device_id: '58:fd:b1:e8:0f:68',
  auth_flag: 'N',
  ignore_disable: 'N',
  eco_info: '01',
  config_key: '00',
  language_code: 'en-GB'
}
[3/19/2021, 11:43:29 PM] [LgWebOsTv] Device: 10.0.0.196 TV, saved Device Info successful: {
  "returnValue": true,
  "features": {
    "dvr": false
  },
  "receiverType": "DVB",
  "modelName": "OLED48CX6LB",
  "programMode": true,
  "product_name": "webOSTV 5.0",
  "model_name": "HE_DTV_W20O_AFABABAA",
  "sw_type": "FIRMWARE",
  "major_ver": "03",
  "minor_ver": "21.16",
  "country": "NO",
  "country_group": "EU",
  "device_id": "58:fd:b1:e8:0f:68",
  "auth_flag": "N",
  "ignore_disable": "N",
  "eco_info": "01",
  "config_key": "00",
  "language_code": "en-GB"
}
[3/19/2021, 11:43:29 PM] [LgWebOsTv] Device: 10.0.0.196 TV, state: Online.
[3/19/2021, 11:43:29 PM] [LgWebOsTv] -------- TV --------
[3/19/2021, 11:43:29 PM] [LgWebOsTv] Manufacturer: LG Electronics
[3/19/2021, 11:43:29 PM] [LgWebOsTv] Model: OLED48CX6LB
[3/19/2021, 11:43:29 PM] [LgWebOsTv] System: webOSTV 5.0
[3/19/2021, 11:43:29 PM] [LgWebOsTv] Serialnr: 58:fd:b1:e8:0f:68
[3/19/2021, 11:43:29 PM] [LgWebOsTv] Firmware: 03.21.16
[3/19/2021, 11:43:29 PM] [LgWebOsTv] ----------------------------------

```

**Comment by grzegorz914** [comment]
Try latest beta .49
