### ISSUE TITLE
inputsFile failed

### ISSUE THREAD

**Issue by donavanbecker** [grzegorz914/homebridge-lgwebos-tv#7]
```
[4/15/2020, 12:23:26 PM] [LgWebOsTv] Device: 192.168.0.108, read inputsFile failed, error: Error: ENOENT: no such file or directory, open '/Users/teresavetter/.homebridge/lgwebosTv/inputs_1921680108'
    at Object.openSync (fs.js:462:3)
    at Object.readFileSync (fs.js:364:35)
    at lgwebosTvDevice.prepareInputServices (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:422:31)
    at lgwebosTvDevice.prepareTvService (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:383:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/username/.homebridge/lgwebosTv/inputs_1921680108'
```

**Comment by grzegorz914** [comment]
In normal case the file is created automatically after HB restart with all inputs and apps installed on the TV but not all TV supports this in its api, or if U change inputs name from HomeKit app.

**Comment by donavanbecker** [comment]
so is there anything that can be done to fix this?

**Comment by grzegorz914** [comment]
Please go to HomeKit app open the TV device settings and change the name of input and press OK.
The error will no longer appear.

**Comment by donavanbecker** [comment]
Thanks
