### ISSUE TITLE
Some timeouts in the connection process

### ISSUE THREAD

**Issue by aberthil** [grzegorz914/homebridge-lgwebos-tv#71]
Here are the issues I am getting. What do you recommend to do here?

[12/6/2020, 8:45:32 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, connected.
[12/6/2020, 8:45:32 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Power state successful: ON
[12/6/2020, 8:45:32 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, RC socket connected.
[12/6/2020, 8:45:33 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, state: Online.
[12/6/2020, 8:45:33 AM] [LgWebOsTv] -------- Master TV --------
[12/6/2020, 8:45:33 AM] [LgWebOsTv] Manufacturer: LG Electronics
[12/6/2020, 8:45:33 AM] [LgWebOsTv] Model: 55NANO90UNA
[12/6/2020, 8:45:33 AM] [LgWebOsTv] System: webOSTV 5.0
[12/6/2020, 8:45:33 AM] [LgWebOsTv] Serialnr: 58:fd:b1:bd:c7:e4
[12/6/2020, 8:45:33 AM] [LgWebOsTv] Firmware: 21.05
[12/6/2020, 8:45:33 AM] [LgWebOsTv] ----------------------------------
[12/6/2020, 8:45:42 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:45:47 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:45:52 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:45:57 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:46:02 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:46:07 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:46:12 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:46:17 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:46:22 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:46:27 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:46:32 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:46:37 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:46:42 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:46:47 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:46:52 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:46:57 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:47:02 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:47:07 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:47:12 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:47:17 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:47:22 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:47:28 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:47:33 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:47:38 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:47:43 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:47:48 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:47:53 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:47:58 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:48:03 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:48:08 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:48:13 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:48:18 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:48:23 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:48:28 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:48:33 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:48:38 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:48:43 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).
[12/6/2020, 8:48:48 AM] [LgWebOsTv] Device: 192.168.1.47 Master TV, get current Channel and Name error: Error: timeout
    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-lgwebos-tv/node_modules/lgtv2/index.js:228:32)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7).

**Comment by grzegorz914** [comment]
Timeout are always network problem.
