### ISSUE TITLE
homebridge-lgwebos-tv v1.6.8-beta.76 - Accessory is not responding

### ISSUE THREAD

**Issue by alexsalex** [grzegorz914/homebridge-lgwebos-tv#82]
subj

**Comment by alexsalex** [comment]
homebridge-lgwebos-tv v1.6.8-beta.79 

same issue

**Comment by alexsalex** [comment]
homebridge-lgwebos-tv v1.6.8-beta.80

same issue

**Comment by felipetng** [comment]
same issue. I just updated and crashed my config

**Comment by grzegorz914** [comment]
get the log please

**Comment by treforparr** [comment]
TypeError: Cannot read property 'length' of undefined
    at lgwebosTvDevice.prepareAccessory (/home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:703:25)
    at new lgwebosTvDevice (/home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:196:8)
    at HomebridgeAPI.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:43:28)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/api.js:81:14)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:160:18)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by treforparr** [comment]
They might be in the same issue keeps crashing my log

**Comment by alexsalex** [comment]
So the developer is pretty weak, who post a beta in main repo... I will tell you.

The code was modifide, please, just remove the TV from Apple Home Kit, and add it again.

**Comment by grzegorz914** [comment]
This is already fixed
