### ISSUE TITLE
Constant crashes

### ISSUE THREAD

**Issue by treforparr** [grzegorz914/homebridge-lgwebos-tv#83]
Constant crashes with log can't reset the device ￼￼

**Comment by treforparr** [comment]
Again this plug-in is still not working properly

**Comment by grzegorz914** [comment]
Log

**Comment by treforparr** [comment]
22/02/2021, 8:29:00 pm TypeError: this.televisionService.getCharacteristic(...).onGet is not a function
    at lgwebosTvDevice.prepareAccessory (/home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:416:5)
    at new lgwebosTvDevice (/home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:206:9)
    at HomebridgeAPI.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:44:28)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/api.js:81:14)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:160:18)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by treforparr** [comment]
This is started since the new work date and trying to get it working all day, do you remember I had problems at the beginning,

**Comment by grzegorz914** [comment]
U need Homebridge min. 1.3.0

**Comment by grzegorz914** [comment]
I close this because not a plugin problem, please install hb 1.3.x
