### ISSUE TITLE
Issue with latest update.

### ISSUE THREAD

**Issue by notorioustubze** [grzegorz914/homebridge-lgwebos-tv#84]
Hi Grzegorz, latest update broke homebridge for me running latest version of Homebridge 1.3.0

![E86ACF59-1AF5-413E-90DD-398C1DB62C74](https://user-images.githubusercontent.com/53260708/108722460-17469300-751b-11eb-9d42-e2968f90f7ce.png)

rolling back to previous version resolved issue.

**Comment by Brwndude2160** [comment]
I am having the same issue after the new re released update. would not let the homebridge start.

**Comment by grzegorz914** [comment]
Please enable debug mode and get the log, here is all OK

**Comment by Brwndude2160** [comment]
> Please enable debug mode and get the log, here is all OK

[22/02/2021, 09:56:25] [LgWebOsTv] didFinishLaunching
[22/02/2021, 09:56:25] [LgWebOsTv] prepareAccessory
[22/02/2021, 09:56:25] [LgWebOsTv] prepareInformationService
[22/02/2021, 09:56:25] [LgWebOsTv] Device: 192.168.1.22 LG TV, readData failed, error: Error: ENOENT: no such file or directory, open '/var/lib/homebridge/lgwebosTv/devInfo_192168122'
    at Object.openSync (fs.js:476:3)
    at Object.readFileSync (fs.js:377:35)
    at lgwebosTvDevice.prepareAccessory (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:373:33)
    at new lgwebosTvDevice (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:197:9)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:43:28)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:125:14) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/var/lib/homebridge/lgwebosTv/devInfo_192168122'
}
[22/02/2021, 09:56:25] TypeError: Cannot read property 'Model' of undefined
    at lgwebosTvDevice.prepareAccessory (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:384:30)
    at new lgwebosTvDevice (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:197:9)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:43:28)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:125:14)



I had to revert back to 1.6.7 for the plugin to work properly

**Comment by notorioustubze** [comment]
Still broken for me installing update breaks homebridge.

**Comment by grzegorz914** [comment]
get your log

**Comment by notorioustubze** [comment]
[22/02/2021, 16:48:27] [LgWebOsTv] didFinishLaunching
[22/02/2021, 16:48:27] [LgWebOsTv] prepareAccessory
[22/02/2021, 16:48:27] [LgWebOsTv] prepareInformationService
[22/02/2021, 16:48:27] [LgWebOsTv] Device: 192.168.0.10 Living Room TV, readData failed, error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at lgwebosTvDevice.prepareAccessory (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:370:24)
    at new lgwebosTvDevice (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:194:9)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:44:28)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:125:14)
[22/02/2021, 16:48:27] [LgWebOsTv] prepareTelevisionService
[22/02/2021, 16:48:27] [LgWebOsTv] prepareSpeakerService
[22/02/2021, 16:48:27] [LgWebOsTv] prepareInputsService
[22/02/2021, 16:48:27] TypeError: Cannot read property 'length' of undefined
    at lgwebosTvDevice.prepareAccessory (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:660:25)
    at new lgwebosTvDevice (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:194:9)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:44:28)
    at HomebridgeAPI.emit (events.js:327:22)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:125:14)

**Comment by grzegorz914** [comment]
get Your config, probably U don't have configured any input

**Comment by notorioustubze** [comment]
Just looking now and you are correct there are no inputs however I did previously have them set up. On one of the updates that come up it removed my default inputs and installed every possible input for the tv’s

**Comment by notorioustubze** [comment]
Adding the inputs back into the config has resolved the issue. Thank you for your time.

**Comment by grzegorz914** [comment]
Lates version prevent crash if no inputs are configured
