### ISSUE TITLE
Homebridge wont start after updating plugins

### ISSUE THREAD

**Issue by galbartal** [grzegorz914/homebridge-lgwebos-tv#89]
2/27/2021, 10:17:47 PM TypeError: this.televisionService.getCharacteristic(...).onGet is not a function
    at lgwebosTvDevice.prepareAccessory (/home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:414:5)
    at new lgwebosTvDevice (/home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:205:9)
    at HomebridgeAPI.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-lgwebos-tv/index.js:44:28)
    at HomebridgeAPI.emit (events.js:228:7)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/@hoobs/hoobs/node_modules/homebridge/lib/api.js:81:14)
    at Server.start (/usr/local/lib/node_modules/@hoobs/hoobs/bridge/server.js:160:18)
    at /usr/local/lib/node_modules/@hoobs/hoobs/bridge/cli.js:94:16
    at processTicksAndRejections (internal/process/task_queues.js:94:5)

**Comment by grzegorz914** [comment]
https://github.com/grzegorz914/homebridge-lgwebos-tv#note
