### ISSUE TITLE
Error: Unexpected end of JSON input

### ISSUE THREAD

**Issue by pespinel** [grzegorz914/homebridge-lgwebos-tv#94]
After updating to version 1.7.55 I can see this error in the Homebridge logs:

```
[24/03/2021, 21:36:43] SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at lgwebosTvDevice.prepareAccessory (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:414:76)
    at new lgwebosTvDevice (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:157:9)
    at HomebridgeAPI.<anonymous> (/usr/local/lib/node_modules/homebridge-lgwebos-tv/index.js:45:28)
    at HomebridgeAPI.emit (events.js:315:20)
    at HomebridgeAPI.signalFinished (/usr/local/lib/node_modules/homebridge/src/api.ts:275:10)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:173:14)
```

**Comment by pespinel** [comment]
Working again after updating to v1.7.56

Thanks!
